### ISSUE TITLE
3.17.0+ eks.NodeGroup instanceTypes breaking change results in replacement

### ISSUE THREAD

**Issue by kennyjwilli** [pulumi/pulumi-aws#1259]
In pulumi/aws 3.16.0, `aws.eks.NodeGroup` accepts `instanceTypes` as a `pulumi.Input<string>`. In 3.17.0, a breaking change was made to switch to `pulumi.Input<pulumi.Input<string>[]>`. This results in Pulumi thinking it needs to replace the `aws:eks:NodeGroup` resource. This is not an acceptable solution. A replacement would result in **deleting** the node group and then re-creating it, taking the service completely offline. This was occurring with the following dependencies. 

```
"@pulumi/pulumi": "2.15.4",
"@pulumi/kubernetes": "2.7.4",
"@pulumi/eks": "0.20.0",
"@pulumi/awsx": "0.22.0",
"@pulumi/aws": "3.19.2",
```

I have worked around this issue by exporting the stack, changing the field to an array, importing, and then running pulumi up. Tricky, but appears to work.

**Comment by tmehlinger** [comment]
This is still a serious issue that causes downtime for EKS clusters. The underlying problem is that the order of the instance types given in the configuration isn't compared as a _set_ to what's in state, and the order of the instance types read from configuration appears to be non-deterministic. This results in the detection of a false difference in the resources, forcing a replacement of the Node Group.

My team is working around this by sorting the instance types we pass to the `NodeGroup` resource but this really needs a fix in the provider.

**Comment by tmehlinger** [comment]
Actually, looking more closely into this, it appears it has been fixed in more recent providers but it still constitutes a breaking change if you're updating from the bugged provider to the fixed provider. Newer versions of the provider appear to sort the input in reverse order, then present that to AWS and store in state. It would be better for this to do a set comparison of the instance types, detect any changes in the set, and then present the list to AWS in the same order recorded in state.

**Comment by tmehlinger** [comment]
For anyone else running into this, I was able to work around it by exporting stack state, changing the order of `instanceTypes` to the order Pulumi expected to produce during the replacement, then imported the modified state.

**Comment by lukehoban** [comment]
The behaviour will be defined by the upstream provider.  

> Actually, looking more closely into this, it appears it has been fixed in more recent providers but it still constitutes a breaking change if you're updating from the bugged provider to the fixed provider. 

Yes - this sounds correct. Related to https://github.com/hashicorp/terraform-provider-aws/pull/21404 and https://github.com/hashicorp/terraform-provider-aws/pull/20532 and https://github.com/hashicorp/terraform-provider-aws/pull/13340.

I don't believe there is anything additional that can be done at this point, beyond having this issue as a record of potential upgrade paths from older provider versions.
