### ISSUE TITLE
Updating to 3.23.0 causes error with RDS cluster_identifier

### ISSUE THREAD

**Issue by sean1588** [pulumi/pulumi-aws#1299]
When updating to the latest version (currently 3.23.0) from 3.12.2 of the AWS provider we are seeing the following error when running an update concerning the database cluster_identifier claiming it to be invalid for the `aws.rds.Cluster` resource. We are also using lateest version (2.17.0) of the CLI.

```
aws:rds:Cluster (databaseCluster):
    error: aws:rds/cluster:Cluster resource 'databaseCluster' has a problem: only lowercase alphanumeric characters and hyphens allowed in "cluster_identifier"
```
This is not a field that we are explicitly defining, it was being set by the provider. We think this could possibly be because this field was recently marked as auto-named. Currently the only workaround we have found for this is explicitly specifying the value by hard coding the same cluster_identifier value specified in the checkpoint file.

**Comment by komalali** [comment]
The **TL;DR** here is that we accidentally shipped a breaking change and reverting it is not an option because that would be a breaking change for anyone who created an RDS cluster after the change was introduced (v3.13.0). An explanation of the issue and suggested workarounds are described below.

This error arose because we marked `clusterIdentifier` as an auto-named property. There are two issues with this:
  1. **Auto-naming adds a random suffix to the resource name**. If the resource name has a capitalized character (i.e. `dbCluster`), the autoname would be `dbCluster-[random-characters-or-numbers]`. But, the cluster identifier property can only have lower cased characters. This is fixed by #1300 which will lowercase all characters when creating the clusterIdentifer, so the result will be `dbcluster-[random-characters-or-number]`. So anyone creating a new cluster will not hit this issue again.
  2. **It was already being auto-named by the underlying tf provider**. This means that anyone who created a cluster with pulumi-aws v3.12.2 or earlier and **did not** specify a `clusterIdentifier` in their program that upgrades to a new version of the provider will cause a forced replacement on update because the cluster identifier will have changed (from the tf autonamed to the pulumi autonamed).

**Workarounds**

1. You can specifically set the `clusterIdentifier` in your program to the existing auto-generated name which follows the pattern `tf-[random-numbers-and-characters]`. To check the value of the existing `clusterIdentifier`, you can export the stack with `pulumi stack export` and check the `outputs` for your cluster and the `clusterIdentifier` should be listed there.
2. If you have many stacks each with a different db cluster, workaround 1 might not be an option. In this case you will have to manually edit the exported stack json and re-import it.
	1) Export your stack with `pulumi stack export > stack.json`
    2) Open `stack.json` in a text editor, copy the `"clusterIdentifier": [value]` line from `outputs` and add it to `inputs`.
    3) Update the `"__defaults"` list in `inputs` to include `"clusterIdentifier"`.
    4) Re-import your stack with `pulumi stack import --file stack.json`.

:pray: Apologies for any grief this may have caused you :pray:

**Comment by sean1588** [comment]
thank you @komalali!

**Comment by komalali** [comment]
After thinking it through some more we realized that reverting is not a breaking change, so we will revert the auto-naming of RDS clusters.
