### ISSUE TITLE
explicit provider not using the aws:profile etc config keys

### ISSUE THREAD

**Issue by rtoma** [pulumi/pulumi-aws#1307]
With config:

```
KEY          VALUE
aws:profile  myprofile
aws:region   us-east-1
```

And code:
```
import pulumi
from pulumi_aws import cloudwatch, Provider


cloudwatch.LogGroup('lg-in-default-region')

provider = Provider('euw1', region='eu-west-1')

cloudwatch.LogGroup(
    'lg-in-euw1', opts=pulumi.ResourceOptions(provider=provider))
```

The configured AWS profile has enough permissions so I would expect two log groups. But in reality the implicit provider succeeds, but the explicit one fails with:
```
Diagnostics:
  aws:cloudwatch:LogGroup (lg-in-euw1):
    error: 1 error occurred:
    	* error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
```

I would expect an explicit provider's to be configured with the same settings as the implicit one, unless explicitly configured.

I searched for a way to read settings from the default provider, to configure to new provider. But no luck. Feel free to point me to docs / source.

When I set env var `AWS_PROFILE` it works, so the explicit provider picks up env vars, but not stack config vars. 

TIA

**Comment by lukehoban** [comment]
It is currently by design that an explicit provider is configured independent of any `aws:*` config.  This is in part because there is a fair bit of mutually exclusive configuration, and so inheriting `aws:*` config may make it very difficult to reason about what was being overridden - or even what configuration was being used.  You can think of `aws:*` config as being the configuration for the implicit provider, and what's passed to `Provider(...)` as the configuration for an explicit provider.  In both case, you specify any configuration settings you want directly (aside from what is picked up as fallbacks in the environment).  

> I searched for a way to read settings from the default provider, to configure to new provider. But no luck. Feel free to point me to docs / source.

These can be read either via either:
* `config = pulumi.Config("aws")` to read the raw input configuration values from the `aws:*` namespace.  See https://www.pulumi.com/docs/intro/concepts/programming-model/#reading-configuration-values.
* `aws.config.profile` to read the resulting values of the configuration - which may also be populated via environment variables.
