### ISSUE TITLE
Attaching the role policy to lambda function doesn't work 

### ISSUE THREAD

**Issue by volkanunsal** [pulumi/pulumi-aws#1308]
Hi there. I have a lambda function that needs to be inside a VPC, so I attach the managed policy `arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole` to it right after defining it

```ts
const importHandler = new aws.lambda.CallbackFunction(
      'sso-eagle3-import-handler',
      {
        vpcConfig,
        memorySize: 6144,
        callback: async (req: any, _ctx: any, cb: any) => {
          return import('./').then((m) => m.handleStart(req, cb, env));
        },
      }
    );

    const policyArn =
      'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole';

    const att1 = new aws.iam.RolePolicyAttachment(
      'sso-eagle3-import-handler-execution-role-policy',
      {
        role: importHandler.role,
        policyArn,
      }
    );
```

However, I still keep getting an error message that indicates the policy is not attached. 

```
The provided execution role does not have permissions to call CreateNetworkInterface on EC2
```

I think I'm doing everything correctly here. I'm wondering if this is  a bug.

**Comment by leezen** [comment]
Could you please provide the resulting diffs from your program execution? Does it include the role policy attachments that you expect?

**Comment by MadSciencist** [comment]
Experiencing the same. Looks like pulumi is not adding the RolePolicyAttachment to the role. It looks all right from the pulumi console resource view, just the resource is not created in the AWS.

**Comment by albertocorrales** [comment]
yep, we are having the same issue. Apparently the problem is the fact that pulumi thinks that the policy attachement was created (as this is displayed in resources stack), but it wasn't. Hence, the deployment fails. 

In our experience this is not happening always. Sometimes it works and it creates the policy attachment properly, but sometimes it doesn't. I'm not sure why

**Comment by lukehoban** [comment]
The issue is that the `aws.lambda.Function` is being created before the `aws.iam.RolePolicyAttachment` is added, and this triggers the error in question.

If you ensure that the role and its attachments are created before the Function, you will not hit this.

This reply is the easiest way to ensure this: https://github.com/pulumi/pulumi-aws/issues/1308#issuecomment-876530939

For the comment about creating an independent role and attaching policies, that is totally fine as well - but you would need to ensure you use `dependsOn` to make sure the Function waits to create until after those role policy attachments are applied.  Otherwise, there is no way to know there is a dependency, and the policy attachments and Function will be created in parallel.  This may mean that sometimes the policy is attached before the Function so that things work, and sometime not.
