### ISSUE TITLE
Auto-generated names when moving resources between stacks

### ISSUE THREAD

**Issue by estyrke** [pulumi/pulumi-aws#1341]
I am trying to refactor my stacks a bit, and so have moved some resources from the main project to a new project. I did this by adding `import` options for the resources in the new project, and then did `pulumi state delete` on them in the old project. However, the crux is that most of the resources had auto-generated names, meaning that I had to explicitly name them in the new project, just copy/pasting the original generated names into the code, to get the import to go through. I was hoping to be able to remove these explicit names after the import by using the `aliases` option, however this does not seem to work (I get a diff for the name property on `pulumi up`). I tried both `aliases: [{name: "old-name" }]`, `aliases: [{stack: "old-stack", project: "old-project"}]` and `aliases: [{name: "old-name", stack: "old-stack", project: "old-project"}]`.

The reason I want to get rid of the `name` tags is that I have prod/dev stacks set up, and the names are of course different in the two, so then I'd need some kind of list with all the prod+dev names from the old project and look them up in the new project, which will get really ugly.

Is there something I can do at this stage to get Pulumi to match the resources correctly? Or is there something I can do at import time to avoid this issue? I'm using an S3 bucket as backend, btw, if that has any bearing.

**Comment by lukehoban** [comment]
When you refer to `name` do you mean:
1. The logical name of the resource, which is then used to auto-generate a physical name
2. An explicit physical `name: ` passed to resource 
3. A `Name` tag on a resource like an EC2 instance?


Also - what specific resource are you working with?

**Comment by estyrke** [comment]
@lukehoban Thanks for the quick reply! I mean the physical name. The logical names (i.e. first argument to the resource constructor) are the same in both new and old stacks. This concerns some AWS resources, so while most are called `name:`, there are also a `bucket` and a `statementId´. To be specific, I have this issue with `aws.iam.Role`, `aws.s3.Bucket`, `aws.dynamodb.Table`, `aws.iam.RolePolicy`, `aws.lambda.Function`, `aws.lambda.Permission`, `aws.ses.ReceiptRule`, `aws.iam.User`, `aws.iam.UserPolicy`. In practice, I only really care about the bucket and dynamodb table, since the others are cheap to recreate.

**Comment by ghostsquad** [comment]
I ran into a similar issue. When importing an s3 bucket, it requires that I set some values that would otherwise not be required by me to set (default provided by the provider), which are the `arn` and the `hostedZoneId`.

Looking at the `hostedZoneId`, the terraform provider hard codes a table of these hostedzones:
https://docs.aws.amazon.com/general/latest/gr/s3.html

https://github.com/hashicorp/terraform-provider-aws/blob/722c1f1fc8fb9fe4371d63d51a21df6397f6a5fd/internal/service/s3/hosted_zones.go#L40

What I don't understand is why does the code actually have to match all attributes when some of the attributes are computed and only need to be stored in state.

**Comment by iwahbe** [comment]
Auto-naming uses data that is not in the cloud, so `pulumi import` won't work. Before this is fixed, you can do manual state surgery to copy in the full state of the resource. This will get auto-naming to work as expected.

Ultimately, the solution to this issue is for Pulumi to natively support transferring resources between stacks/projects. We have an open issue for that in pulumi/pulumi: https://github.com/pulumi/pulumi/issues/3389.
