### ISSUE TITLE
Error running pulumi-aws in CI environment when assuming a role for credentials

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-aws#1359]
The code would effectively be doing the following:

```
const provider = new aws.Provider("provider-name", {
    skipCredentialsValidation: false,
	skipMetadataApiCheck: false,
	region: <region name>,
	profile: <empty string>,
})
```

This is working in 3.23.0 but not in 3.29.1 and would be using an IAM Role to get the credentials. The error message is:

```
 error: 1 error occurred:
     	* error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
     Please see https://registry.terraform.io/providers/hashicorp/aws
     for more information about providing credentials.
     Error: NoCredentialProviders: no valid providers in chain. Deprecated.
     	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Comment by DavidHe1127** [comment]
We are hit by this error as well. Proposed fix mentioned in #1354 does not work for us. `3.28.0` is working perfectly until we upgrade it to `3.28.1`. See the error from BuildKite below:

```
[2021-02-24T05:54:16Z] [infra:preview] error: Preview failed: 1 error occurred:
--
  | [2021-02-24T05:54:16Z] [infra:preview] 	* error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
  | [2021-02-24T05:54:16Z] [infra:preview]
  | [2021-02-24T05:54:16Z] [infra:preview] Please see https://registry.terraform.io/providers/hashicorp/aws
  | [2021-02-24T05:54:16Z] [infra:preview] for more information about providing credentials.
  | [2021-02-24T05:54:16Z] [infra:preview]
  | [2021-02-24T05:54:16Z] [infra:preview] Error: EC2RoleRequestError: no EC2 instance role found
  | [2021-02-24T05:54:16Z] [infra:preview] caused by: RequestCanceled: EC2 IMDS access disabled via AWS_EC2_METADATA_DISABLED env var
```

**Comment by piclemx** [comment]
Hey @DavidHe1127 ,

@stack72  was mentioning this morning to try to used this instead
```
pulumi config set aws:skipCredentialsValidation false
pulumi config set aws:skipGetEc2Platforms false
pulumi config set aws:skipMetadataApiCheck false
```

**Comment by DavidHe1127** [comment]
@piclemx Thanks for swift response. I will give it a go and let you know

**Comment by DavidHe1127** [comment]
@piclemx I tried setting them in config file but it didn't work. I assume they are the same as doing them in command line?

```
config:
  aws:skipMetadataApiCheck: false
  aws:skipGetEc2Platforms: false
  aws:skipCredentialsValidation: false
```

Also, what is the drive for the change in authentication behaviour?

**Comment by dferretti** [comment]
@DavidHe1127 the change is from here https://github.com/pulumi/pulumi-aws/pull/1288 and looks to be for speed reasons. It allows them to skip several seconds' worth of work attempting to fetch EC2 metadata credentials and other requests. We were bitten by this too since we run all our pulumi from a build server we host in AWS.

And we also don't make the change in config - I think that only affects the default aws provider, but we always create our own providers manually (because there are usually multiple providers) and pass them in explicitly to resources so in code for us that looks like
```c#
var awsProvider = new Pulumi.Aws.Provider("aws-provider", new Pulumi.Aws.ProviderArgs
{
    ....
    SkipMetadataApiCheck = false,
});
```

**Comment by stack72** [comment]
Hi @dferretti 

If these config values work for you, then I will also add a guide to the README to suggest `### Running Pulumi-Aws in CI environments` so that others don't get bitten

P.

**Comment by dferretti** [comment]
I can say I saw the same `NoCredentialProviders: no valid providers in chain. Deprecated.` error after bumping from 3.28.0 to 3.29.1, and since adding that property in c# I can now run 3.29.1 successfully 👍

**Comment by stack72** [comment]
ok..... we need a new section in our README about what these changes we made did and how it will affect certain conditions

thank you so much for this @dferretti

**Comment by dferretti** [comment]
Thank you!

**Comment by orionstudt** [comment]
@stack72 I think you need to re-word the original opener of this issue. It is very confusing the way that it is originally written.

In 3.28.0 this would work:
```
const provider = new aws.Provider("provider-name", {
	region: <region name>,
	profile: <empty string>,
})
```

Because the default of `SkipMetadataApiCheck` was `false`. As such this code in your original comment would also work in 3.28.0 because you're not changing the default:
```
const provider = new aws.Provider("provider-name", {
        skipCredentialsValidation: false,
	skipMetadataApiCheck: false,
	region: <region name>,
	profile: <empty string>,
})
```

But your original comment states that the above sample would not work in 3.29.1. That is false. It would work, because it resolves the default of `SkipMetadataApiCheck` being changed to `true`. Instead, this is what no longer works in 3.29.1:
```
const provider = new aws.Provider("provider-name", {
	region: <region name>,
	profile: <empty string>,
})
```

**Comment by DavidHe1127** [comment]
Ok. I can confirm setting those values in code DID NOT work for me:

```
const provider = new aws.Provider(`${stack}-dev`, {
  region: 'ap-southeast-2',
  profile: 'dev',
  skipCredentialsValidation: false,
  skipMetadataApiCheck: false,
});
```

My envs:

```
"@pulumi/aws": "3.28.1",
"@pulumi/awsx": "0.22.0",
"@pulumi/pulumi": "2.16.2",
```
I run Pulumi inside a container which is booted by `pulumi/pulumi-nodejs:2.16.2`.

We currently have to downgrade it to `3.28.0` to bypass the error.

**Comment by thepatrick** [comment]
We are seeing a slight variation of the error:

```
[2021-02-24T03:45:26Z] error: Preview failed: 1 error occurred:
--
  | [2021-02-24T03:45:26Z] 	* error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
  | [2021-02-24T03:45:26Z]
  | [2021-02-24T03:45:26Z] Please see https://registry.terraform.io/providers/hashicorp/aws
  | [2021-02-24T03:45:26Z] for more information about providing credentials.
  | [2021-02-24T03:45:26Z]
  | [2021-02-24T03:45:26Z] Error: EC2RoleRequestError: no EC2 instance role found
  | [2021-02-24T03:45:26Z] caused by: RequestCanceled: EC2 IMDS access disabled via AWS_EC2_METADATA_DISABLED env var
```

With the 
```
"@pulumi/aws": "3.28.1",
"@pulumi/awsx": "0.22.0",
"@pulumi/pulumi": "2.16.2",
```

I'm curious why this breaking change was made in a patch release

**Comment by dferretti** [comment]
@DavidHe1127 I have one more idea that might help, and then I'll leave it to people who know more than me. 

I do remember now that even after making the config change it did not work right away for me. Our pipeline ran these steps
```
pulumi plugin install ..
pulumi refresh ...
pulumi up ...
```
It would still fail, and I believe it was because our state file from a previous failed attempt saved the config used with the setting missing. So the `refresh` step would fail since it was looking at my old configuration. Once I removed the `refresh` step temporarily and ran it, everything worked fine. And then after 1 successful run I was able to put the refresh step back in there and continue working.

**Comment by piclemx** [comment]
Any news on this?

**Comment by leezen** [comment]
For folks coming into this issue, here's a summary of where I think things stand:
1. You should be able to set `skipCredentialsValidation: false` and `skipMetadataApiCheck: false` in order to assume the IAM role correctly in CI/EC2.
2. If you're updating an existing stack which has an older version of the plugin, but has failed an update, you may need to first `pulumi up` to ensure it's using the latest plugin before you `pulumi refresh` per @dferretti's suggestion to make sure that it's running with both the correct configuration and latest plugin.
3. If you're still seeing issues after trying the above, please document your configuration, versions, and environment information. So far, we've been unable to reproduce the error once the correct configuration is set.

**Comment by piclemx** [comment]
> For folks coming into this issue, here's a summary of where I think things stand:
> 
> 1. You should be able to set `skipCredentialsValidation: false` and `skipMetadataApiCheck: false` in order to assume the IAM role correctly in CI/EC2.
> 2. If you're updating an existing stack which has an older version of the plugin, but has failed an update, you may need to first `pulumi up` to ensure it's using the latest plugin before you `pulumi refresh` per @dferretti's suggestion to make sure that it's running with both the correct configuration and latest plugin.
> 3. If you're still seeing issues after trying the above, please document your configuration, versions, and environment information. So far, we've been unable to reproduce the error once the correct configuration is set.

I can retry @leezen, but the given step wasn't working for me with the latest version of the provider. I'm never do the `refresh` step in the pipeline before running the `up` command.

**Comment by DavidHe1127** [comment]
> 1. skipMetadataApiCheck

We run `preview` rather than `up` and with all other suggested setup, we are still seeing the same error.

```
    "@pulumi/auth0": "1.8.1",
    "@pulumi/aws": "3.30.1",
    "@pulumi/awsx": "0.25.0",
    "@pulumi/pulumi": "2.21.2",
```
`preview` step is run in `public.ecr.aws/pulumi/pulumi-nodejs:2.21.2`. 

```
export const awsProvider = new Provider('aws-provider', {
  region,
  profile: config.require('profile'),
  skipCredentialsValidation: false,
  skipMetadataApiCheck: false,
});
```

**Comment by DavidHe1127** [comment]
Even with 2 flags set to `false`, i still see they are `true` during preview?

```
[2021-03-09T02:37:06    ~ pulumi:providers:aws: (update)
--
  | [2021-03-09T02:37:06Z] [infra:up]         [id=d5baef68-xxxx-40bd-xxxx-f633b785c804]
  | [2021-03-09T02:37:06Z] [infra:up]         [urn=urn:pulumi:xxxxxx::xxxxxx-tester::pulumi:providers:aws::xxxxxx-dev]
  | [2021-03-09T02:37:06Z] [infra:up]         profile                  : "kasada-dev"
  | [2021-03-09T02:37:06Z] [infra:up]         region                   : "ap-southeast-2"
  | [2021-03-09T02:37:06Z] [infra:up]       + skipCredentialsValidation: "true"
  | [2021-03-09T02:37:06Z] [infra:up]       + skipGetEc2Platforms      : "true"
  | [2021-03-09T02:37:06Z] [infra:up]       + skipMetadataApiCheck     : "true"
  | [2021-03-09T02:37:06Z] [infra:up]       + skipRegionValidation     : "true"
```

@leezen Can you share the code example you proved worked?

**Comment by DavidHe1127** [comment]
Checked the source code and found this

3.28.0
```
exports.skipCredentialsValidation = __config.getObject("skipCredentialsValidation");
```

3.28.0+
```
exports.skipCredentialsValidation = __config.getObject("skipCredentialsValidation") || true;
```
Shouldn't be `??` instead of `||`?

**Comment by leezen** [comment]
Thanks for pointing that line out. That actually shouldn't affect it since that's not used to construct the provider, but looking at the generated code for `provider.ts` I see https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/provider.ts#L56 which has this same logic. As a result, I think this bug would manifest itself in explicitly constructed providers, but not the default provider, which might explain a miss in our repro attempt.

**Comment by stack72** [comment]
Hi all

Based on the investigation work by @DavidHe1127 and @leezen, I was able to find that there was indeed a bug in named providers that stopped values being used that were not the default

I was able to fix that in https://github.com/pulumi/pulumi/pull/6496

This work has made it's way down to the pulumi-aws provider as **v3.32.1** and we believe this now means that you can set your values as expected and you should be able to authenticate in an EC2 environment with the iam role.

Your code would need to be something like this:

```
const prov = new aws.Provider("named-provider", {
    region: "us-west-2",
    skipMetadataApiCheck: false,
    skipGetEc2Platforms: false,
});
```

and it will pick up the creds

I am going to close this issue out BUT IF THERE ARE ANY FURTHER ANOMOLIES then please do comment and we can reopen and investigate further if needed

Thanks again for your patience here and we can't thank you enough for helping us track down this bug

Paul

**Comment by yann-soubeyrand** [comment]
Hello @stack72,

We’re using Pulumi v3.37.2 with AWS provider v5.10.0 in Go. We disabled all default providers. We’re creating an AWS provider using the following code
```
awsProvider, err = aws.NewProvider(ctx, "main",
	&aws.ProviderArgs{
		SkipMetadataApiCheck: pulumi.Bool(false),
		Region:               pulumi.String("eu-west-1"),
	},
)
```

We’re still seeing this in `pulumi preview --diff`
```
    + pulumi:providers:aws: (create)
        [urn=urn:pulumi:test::test::pulumi:providers:aws::main]
        region                   : "eu-west-1"
        skipCredentialsValidation: false
        skipGetEc2Platforms      : true
        skipMetadataApiCheck     : true
        skipRegionValidation     : true
        version                  : "5.10.0"
```

And we’re still having this error in the log on the CI machine using AWS instance profile
`error: unable to validate AWS credentials - see https://pulumi.io/install/aws.html for details on configuration`

Did we miss something or has this bug reappeared?

**Comment by piclemx** [comment]
@yann-soubeyrand try with this

```
awsProvider, err = aws.NewProvider(ctx, "main",
	&aws.ProviderArgs{
		SkipMetadataApiCheck: pulumi.Bool(true),
		Region:               pulumi.String("eu-west-1"),
	},
)
```

For some reason, the logic has been reverse in the terraform provider if I understand correctly

**Comment by stack72** [comment]
Hi @yann-soubeyrand 

Are you trying to authenticate via the Ec2 Metadata API? If so, then you can skip credentials validation checks as follows:

```
awsProvider, err = aws.NewProvider(ctx, "main",
	&aws.ProviderArgs{
        SkipCredentialsValidation: pulumi.Bool(true),
		SkipMetadataApiCheck: pulumi.Bool(false),
		Region:               pulumi.String("eu-west-1"),
	},
)
```

that *should* fix the issue for you!

Paul

**Comment by hbollon** [comment]
Hi @stack72 
Little follow-up for our problem with @yann-soubeyrand 
With `pulumi.Bool` values we can't set `Skip*` attributes of the `aws.ProviderArgs` struct because they are override by default values according to the pulumi preview output.
For exemple with:
```go
f.awsProvider, err = aws.NewProvider(ctx, "main",
		&aws.ProviderArgs{
			SkipMetadataApiCheck:      pulumi.Bool(false),
			SkipCredentialsValidation: pulumi.Bool(true),
			Region:                    args.Region,
		},
[...]
```
We have this:
```
6:20PM INFO  actions.preview._exec | #11 95.88         + pulumi:providers:aws: (create)
6:20PM INFO  actions.preview._exec | #11 95.88             [urn=urn:pulumi:dev::schweizmobil::foundations:Foundations$pulumi:providers:aws::main]
6:20PM INFO  actions.preview._exec | #11 95.88             region                   : "eu-west-1"
6:20PM INFO  actions.preview._exec | #11 95.88             skipCredentialsValidation: true
6:20PM INFO  actions.preview._exec | #11 95.88             skipGetEc2Platforms      : true
6:20PM INFO  actions.preview._exec | #11 95.88             skipMetadataApiCheck     : true
6:20PM INFO  actions.preview._exec | #11 95.88             skipRegionValidation     : true
6:20PM INFO  actions.preview._exec | #11 95.88             version                  : "5.10.0"
```

However, if we use `pulumi.BoolPtr` instead we have the expected result:
```go
f.awsProvider, err = aws.NewProvider(ctx, "main",
		&aws.ProviderArgs{
			SkipMetadataApiCheck:      pulumi.BoolPtr(false),
			SkipCredentialsValidation: pulumi.BoolPtr(true),
			Region:                    args.Region,
		},
[...]
```
```
7:26AM INFO  actions.preview._exec | #11 105.2         + pulumi:providers:aws: (create)
7:26AM INFO  actions.preview._exec | #11 105.2             [urn=urn:pulumi:dev::schweizmobil::foundations:Foundations$pulumi:providers:aws::main]
7:26AM INFO  actions.preview._exec | #11 105.2             region                   : "eu-west-1"
7:26AM INFO  actions.preview._exec | #11 105.2             skipCredentialsValidation: true
7:26AM INFO  actions.preview._exec | #11 105.2             skipGetEc2Platforms      : true
7:26AM INFO  actions.preview._exec | #11 105.2             skipMetadataApiCheck     : false
7:26AM INFO  actions.preview._exec | #11 105.2             skipRegionValidation     : true
7:26AM INFO  actions.preview._exec | #11 105.2             version                  : "5.10.0"
```

My guess, after having taken a look at the code, is that you have some condition in the `aws.NewProvider` function which call IsZero utility func on those args (skip* and region) in order to set default values if none was provided:
 ```go
if isZero(args.Region) {
	args.Region = pulumi.StringPtr(getEnvOrDefault("", nil, "AWS_REGION", "AWS_DEFAULT_REGION").(string))
}
if isZero(args.SkipCredentialsValidation) {
	args.SkipCredentialsValidation = pulumi.BoolPtr(false)
}
if isZero(args.SkipGetEc2Platforms) {
	args.SkipGetEc2Platforms = pulumi.BoolPtr(true)
}
if isZero(args.SkipMetadataApiCheck) {
	args.SkipMetadataApiCheck = pulumi.BoolPtr(true)
}
if isZero(args.SkipRegionValidation) {
	args.SkipRegionValidation = pulumi.BoolPtr(true)
}
```
And in this `IsZero` function you're performing a test on the default value of the type of the argument:
```go
// isZero is a null safe check for if a value is it's types zero value.
func isZero(v interface{}) bool {
	if v == nil {
		return true
	}
	return reflect.ValueOf(v).IsZero()
}
```

Knowing that, with a bool variable set to **false** as input it seems normal that this function return **true** and so override the arg (SkipMetadataApiCheck in our case) back to **true**.
Is it an intended feature? In your exemples you also used `pulumi.Bool` and not the Ptr equivalent :thinking:

**Comment by stack72** [comment]
That is a bug! Great catch @hbollon - I will open an issue!
