### ISSUE TITLE
deleteBeforeReplace does not work on aws.ec2.SecurityGroupRule

### ISSUE THREAD

**Issue by jeffrichie** [pulumi/pulumi-aws#1451]
Versions:

pulumi-cli: `v2.25.1`
`"@pulumi/aws": "^3.38.1",`

My code:

```
new aws.ec2.SecurityGroupRule(
  `bastion-rule-${env}`,
  {
    type: 'ingress',
    toPort: 0,
    protocol: '-1',
    fromPort: 0,
    securityGroupId: vpc.vpc.defaultSecurityGroupId,
    sourceSecurityGroupId: bastionSecGroup.id
  },
  { deleteBeforeReplace: true }
);
```

When `env` changes, I end up getting:

```
View Live: https://app.pulumi.com/xxxx/xxx-xxx-vpc/development/updates/49
     Type                          Name                                 Status                  Info
     pulumi:pulumi:Stack           xxx-foundations-vpc-development  **failed**              1 error
 +   └─ aws:ec2:SecurityGroupRule  bastion-rule-2137                    **creating failed**     1 error
Diagnostics:
  aws:ec2:SecurityGroupRule (bastion-rule-2137):
    error: 1 error occurred:
    	* [WARN] A duplicate Security Group rule was found on (sg-059e66fdf2c37c5ac). This may be
    a side effect of a now-fixed Terraform issue causing two security groups with
    identical attributes but different source_security_group_ids to overwrite each
    other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
    information and instructions for recovery. Error message: the specified rule "peer: sg-06987771897f711dd, ALL, ALLOW" already exists
```

I would expect the rule to get deleted before it's created due to `deleteBeforeReplace` being `true` on the resource.

**Comment by phillipedwards** [comment]
Additional repro:
Context: changing the name of an existing SG rule causes error. `deleteBeforeReplace` has not impact.

Pulumi stats:
```
▶ pulumi about 
CLI          
Version      3.26.1
Go Version   go1.17.7
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.1.0
docker  3.2.0
nodejs  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64
```

Code:
```typescript
import * as aws from "@pulumi/aws";

const vpcId = "vpc-52e9e62b"; // your vpc id here

const sg = new aws.ec2.SecurityGroup("sut", {
    vpcId: vpcId,
    description: "A test security group",
    revokeRulesOnDelete: true,
});

new aws.ec2.SecurityGroupRule("rename-me-for-error", {
    type: "ingress",
    securityGroupId: sg.id,
    description: "A rule to test renaming",
    self: true,
    protocol: "ALL",
    fromPort: 0,
    toPort: 0,
}, {deleteBeforeReplace: true});
```

**Comment by pgavlin** [comment]
The Pulumi engine uses a resource's name to correlate between its desired state as represented in the Pulumi program and its actual state as stored in the checkpoint file. Renaming a resource changes its logical identity and breaks this correlation, so `deleteBeforeReplace`--which only controls when the resource is deleted if the difference between its desired state and actual state requires that the resource is deleted and recreated--does not apply. Instead, a new, unrelated resource is created and the original resource is deleted. The original resource is deleted at the end of the `pulumi update` because the engine cannot know which resources to delete until the Pulumi program finishes running.

Though it would require some refactoring, you should be able to address this via [`aliases`](https://www.pulumi.com/docs/intro/concepts/resources/options/aliases/) to make the rename visible to the Pulumi engine.

We have an issue to track attempting to detect this situation during `preview` and suggesting the use of aliases (https://github.com/pulumi/pulumi/issues/6078), which may at least help clarify the behavior.
