### ISSUE TITLE
Add AWSLambdaBasicExecutionRole policy to lambdas created through magic functions

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-aws#1461]
At the moment if you have a lambda function created as a magic function, we don't assign the `AWSLambdaBasicExecutionRole` policy which means that you can't log anything.

So this code:

```typescript
import * as aws from '@pulumi/aws';
aws.cloudwatch.onSchedule('log-something', 'rate(5 minutes)', (e) => {
  console.log(`Hello from Scheduler.`);
});
```

Will invoke the function every 5 minutes but won't actually be able to log anything.

**Comment by leezen** [comment]
This looks like a result of https://github.com/pulumi/pulumi-aws/pull/1450/files

@stack72 It's not clear to me why we reverted from old copy of the FullAccess policy to attempting to use the managed version? The managed version simply doesn't have the right set of policies that we wanted to be the default. I think we should re-examine what set of permissions we want to enable by default here since we do want CloudWatch logs to work out of the box.

**Comment by serenitus** [comment]
> we do want CloudWatch logs to work out of the box.

From an end-user POV I totally concur with this. I had just written a Slack message to a colleague declaring Pulumi to be borderline witchcraft and went back to my CloudWatch log groups only to have the magical bubble unceremoniously popped.

**Comment by stack72** [comment]
> This looks like a result of https://github.com/pulumi/pulumi-aws/pull/1450/files
> 
> 
> 
> @stack72 It's not clear to me why we reverted from old copy of the FullAccess policy to attempting to use the managed version? The managed version simply doesn't have the right set of policies that we wanted to be the default. I think we should re-examine what set of permissions we want to enable by default here since we do want CloudWatch logs to work out of the box.

It was called out as an item for our breaking changes to be made in this release

> Swap from the deprecated AWSLambdaFullAccess to AWSLambda_FullAccess as the default for mixins.

If this isn't correct we can always bring back the old copy. When we had to deprecate the aws policy we decided to 'temporarily' add a copy as removing it would be too disruptive outside of a major version

More than happy to revisit this decision and make a new release of the provider today

**Comment by leezen** [comment]
@stack72 I saw that it was called out and it's my bad for not catching that. I agree we didn't want to totally disrupt things from a major version perspective, so it's probably good we reduced the scope as part of going to 4.0. That being said, a lot of common scenarios aren't being covered because `AWSLambda_FullAccess` doesn't quite have enough permissions (most importantly, Cloudwatch Logs) and various mixins in the package won't work correctly without said permissions either.

Previously, when we looked at the deprecation of the old policy, we had the following investigation:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "cloudformation:DescribeChangeSet", # AWSCloudFormationReadOnlyAccess (more permissive)
                "cloudformation:DescribeStackResources", # AWSCloudFormationReadOnlyAccess
                "cloudformation:DescribeStacks", # AWSLambda_FullAccess
                "cloudformation:GetTemplate", # AWSCloudFormationReadOnlyAccess
                "cloudformation:ListStackResources", # AWSLambda_FullAccess
                "cloudwatch:*", # CloudWatchFullAccess
                "cognito-identity:ListIdentityPools", # AmazonCognitoPowerUser (more permissive: *)
                "cognito-sync:GetCognitoEvents", # AmazonCognitoPowerUser 
                "cognito-sync:SetCognitoEvents", # AmazonCognitoPowerUser
                "dynamodb:*", # AmazonDynamoDBFullAccess (more permissive)
                "ec2:DescribeSecurityGroups", # AWSLambda_FullAccess
                "ec2:DescribeSubnets", # AWSLambda_FullAccess
                "ec2:DescribeVpcs", # AWSLambda_FullAccess
                "events:*", # CloudWatchEventsFullAccess
                "iam:GetPolicy", # AWSLambda_FullAccess
                "iam:GetPolicyVersion", # AWSLambda_FullAccess
                "iam:GetRole", # AWSLambda_FullAccess
                "iam:GetRolePolicy", # AWSLambda_FullAccess
                "iam:ListAttachedRolePolicies", # AWSLambda_FullAccess
                "iam:ListRolePolicies", # AWSLambda_FullAccess
                "iam:ListRoles", # AWSLambda_FullAccess
                "iam:PassRole", # AWSLambda_FullAccess (with a condition that it's passed to lambda.amazonaws.com)
                "iot:AttachPrincipalPolicy", # AWSIoTFullAccess (or perhaps drop)
                "iot:AttachThingPrincipal",
                "iot:CreateKeysAndCertificate",
                "iot:CreatePolicy",
                "iot:CreateThing",
                "iot:CreateTopicRule",
                "iot:DescribeEndpoint",
                "iot:GetTopicRule",
                "iot:ListPolicies",
                "iot:ListThings",
                "iot:ListTopicRules",
                "iot:ReplaceTopicRule",
                "kinesis:DescribeStream", # AmazonKinesisFullAccess (more permissive: *)
                "kinesis:ListStreams", #  AmazonKinesisFullAccess
                "kinesis:PutRecord", #  AmazonKinesisFullAccess
                "kms:ListAliases", # AWSLambda_FullAccess
                "lambda:*", # AWSLambda_FullAccess
                "logs:*", # CloudWatchFullAccess
                "s3:*", # AmazonS3FullAccess
                "sns:ListSubscriptions", # CloudWatchFullAccess (more permissive: *)
                "sns:ListSubscriptionsByTopic", # CloudWatchFullAccess
                "sns:ListTopics", # CloudWatchFullAccess
                "sns:Publish", # CloudWatchFullAccess
                "sns:Subscribe", # CloudWatchFullAccess
                "sns:Unsubscribe", # CloudWatchFullAccess
                "sqs:ListQueues", # AmazonSQSFullAccess (more permissive: *)
                "sqs:SendMessage", #AmazonSQSFullAccess
                "tag:GetResources", # AWSLambda_FullAccess
                "xray:PutTelemetryRecords", # AWSXrayWriteOnlyAccess
                "xray:PutTraceSegments" # AWSXrayWriteOnlyAccess
            ],
            "Resource": "*"
        }
    ]
}
```

I think we will want to do a few things:
1) Add `CloudWatchFullAccess` by default -- this way, logging works as do various SNS/SQS scenarios, which are fairly common, especially since other mixins (like `.onSchedule`) will need this as well. I think this should cover the permissions necessary for SQS, SNS, and CloudWatch mixins (we should verify this).
2) We should _consider_ adding S3 and/or DynamoDB full access. Though, here, I think one could argue we should probably err on having the user provide the necessary/appropriate S3/DynamoDB roles.
3) If we don't (2), then we should modify the DynamoDB and S3 mixins to provide the appropriate permissions in order to get the notifications and be able to perform reads/writes.
4) Update the Kinesis mixin to have sane default permissions.

**Comment by stack72** [comment]
Ok, based on what was there before, and the analysis that @leezen made in the old Lambda Access Policy, I have done the following:

## CallbackFunctions now get the following by default:

* LambdaFullAccess
* CloudWatchFullAccess
* CloudWatchEventsFullAccess
* AmazonS3FullAccess
* AmazonDynamoDBFullAccess
* AmazonSQSFullAccess
* AmazonKinesisFullAccess
* AWSCloudFormationReadOnlyAccess
* AmazonCognitoPowerUser
* AWSXrayWriteOnlyAccess

This brings us pretty much back to par with what we had before and we don't maintain a separate copy of a lambda function to get there. Notice I dropped iot permissions as that's very specific and I think users need to create their own IOT permissions around that

## Kinesis Mixins

The kinesis mixin now gets the following default permissions:

* AWSLambdaKinesisExecutionRole
* AmazonKinesisFullAccess
* CloudWatchFullAccess
* CloudWatchEventsFullAccess
* LambdaFullAccess

This is a sane [guess] at what permissions it would need. I am open to changing these of course

These 2 sets of changes allow us to get back to a more working solution and using the Amazon managed policies

**Comment by leezen** [comment]
@benjaminkomen The reason we chose `CloudWatchFullAccess` is that that policy also provides the necessary permissions for interacting with SNS (see https://github.com/pulumi/pulumi-aws/issues/1461#issuecomment-825801144) and still tries to provide a similar level of permissions to what was previously available in the old full access policy that we had originally defaulted to.

**Comment by benjaminkomen** [comment]
@leezen, ok, that makes sense, thanks for the reply!
