### ISSUE TITLE
Pulumi is not triggering configured Instance Refresh after Lanuch Template update. 

### ISSUE THREAD

**Issue by dimitor115** [pulumi/pulumi-aws#1577]
In the pulumi AWS Auto Scaling Group input, there is option to configure triggering Instance Refresh after events like launch template update etc.

The [documentation](https://www.pulumi.com/docs/reference/pkg/aws/autoscaling/group/#instancerefresh_nodejs) says that if the `instanceRefresh` block is configured then pulumi will start the Instance Refresh.
However, I am not observing this behaviour after updating the lunch template, and I need to trigger it from the console manually.

## Steps to reproduce
I've created a simple deployment in pulumi node.js to help you reproduce this scenario, [link](https://github.com/dimitor115/pulumi-instance-refresh-bug-reproduction). There you have detailed reproduction steps etc.
However basically, to reproduce:
1. Launch a deployment containing Auto Scaling Group with `instanceRefresh` option configured and Launch Template.
2. Change sth in the Lauch Temple.
3. Run the deployment again, the pulumi should update the launch temple.
4. Open AWS console, go to ASG section and check that instance refresh was not triggered, despite the documentation says:
> A refresh will always be triggered by a change in any of launch_configuration, launch_template, or mixed_instances_policy.

Expected: Pulumi should trigger Instance Refresh procedure on ASG
Actual: The Instance Refresh is not triggered

Tested on:
Pulumi: `v3.7.0`
Node: `12.x` and `15.x`

**Comment by leezen** [comment]
Unfortunately, I think this is a documentation bug as the [documentation](https://www.pulumi.com/docs/reference/pkg/aws/autoscaling/group/#instancerefresh_nodejs) is derived from the [Terraform documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#instance_refresh) and we seem to have missed including the `NOTE`:

> A refresh is started when any of the following Auto Scaling Group properties change: launch_configuration, launch_template, mixed_instances_policy. Additional properties can be specified in the triggers property of instance_refresh.

Because updating the launch template resource itself doesn't cause an update to any of the ASG properties, instance refresh won't be triggered. If you change from say `$Latest` to `$Default` in your `launchTemplate` section of the autoscaling group resource, you'll see that the instance refresh is triggered.

One way to do this would be something along the lines of:
```
    tags: [{
        key: "userDataHash",
        value: launchTemplate.userData.apply(u => sha256(u)),
        propagateAtLaunch: true,
    }],
    instanceRefresh: {
        strategy: "Rolling",
        preferences: {
            minHealthyPercentage: 50,
        },
        triggers: ["tag"],
    },
```

**Comment by dimitor115** [comment]
@leezen Thank you! I can confirm that the solution you have described work for me 😄

**Comment by cepefernando** [comment]
That solution did the trick @leezen. Even tho the official documentation still doesn't say to update the launchTemplate version value from Latest to Default. 

This is what worked:
```
        launch_template=aws.autoscaling.GroupLaunchTemplateArgs(
            id=launch_templates[typ].id,
            version="$Default",
        ),
```
