### ISSUE TITLE
Error while deleting ECS cluster

### ISSUE THREAD

**Issue by aamir-locus** [pulumi/pulumi-aws#1621]
## Steps to reproduce

`ecsCluster = ecs.Cluster(
            opts=pulumi.ResourceOptions(parent=self),
            resource_name=name,
            name=f"{name}-{name.encode('utf-8').hex()}",
            capacity_providers=clusterType,
            default_capacity_provider_strategies=defaultProvider,
            settings=validate.ecsClusterSetting(),
            tags=tags,
        )`

Creating ECS cluster with the clusterType `ECS`.  Resource created successfully but when I run `pulumi destroy` command it throws an error.
`Error deleting ECS cluster: ClusterContainsContainerInstancesException: The Cluster cannot be deleted while Container Instances are active or draining.`

There's already an issue reported on terraform aws provider for similar use case. https://github.com/hashicorp/terraform-provider-aws/issues/4852.

I am thinking about the workaround where to scale down the instance count to `0` when we run destroy. I am aware about the terraform where it gives `when = destroy` and runs a block when `destroy` operation called.

Is there anything similar to terraform available on pulumi to called a block only on `destroy` operation ?

Expected: 
ECS Cluster should be deleted.

Actual:
`Error deleting ECS cluster: ClusterContainsContainerInstancesException: The Cluster cannot be deleted while Container Instances are active or draining.`

**Comment by lionello** [comment]
This is still a bug. It happens once in a while. In my case `pulumi down` complained that a security group was still in use. It was in use by the task. The ECS service was deleted, but the SG could not be deleted because of the task (that never stopped.) I opened an AWS support case and the suggestion was to always set desired count to 0 before deleting a service.

Now that Pulumi no longer uses TF, the label [awaiting-upstream](https://github.com/pulumi/pulumi-aws/labels/awaiting-upstream) should probably be removed?

**Comment by Zemnmez** [comment]
my pulumi setup is stuck on this. Has anyone determined a workaround?

**Comment by Zemnmez** [comment]
> my pulumi setup is stuck on this. Has anyone determined a workaround?

In my case, I just needed to update.

**Comment by mikhailshilkov** [comment]
The upstream issue has been closed and it sounds like the latest version works. I'll go ahead and close the issue. If anyone is still experiencing the problem, please open a new issue with a repro code snippet.
