### ISSUE TITLE
Create DynamoDB TableItem throws OutputInstance<string | undefined> not assignable

### ISSUE THREAD

**Issue by mcfadyeni** [pulumi/pulumi-aws#1628]
When creating a TableItem with DynamoDB and specifying a range key, Pulumi throws the error
`error TS2322: Type 'Output<string | undefined>' is not assignable to type 'string | Promise<string> | OutputInstance<string> | undefined'.`

## Steps to reproduce

Gist reproduction: https://gist.github.com/mcfadyeni/fa4ce2032c7191e7e4292f67a773cd4b
1. Create a DynamoDB table with a hash key and a range key.
2. Create a TableItem. Example:

```
const dynamoItem = new aws.dynamodb.TableItem("example", {
			tableName: main_table.name,
			hashKey: main_table.hashKey,
			rangeKey: main_table.rangeKey,
			item: '{"hashKey": {"S": "hashKey"}, "rangeKey": {"S": "rangeKey"}'
		})
```
3. Pulumi throws below error:
```
error TS2322: Type 'Output<string | undefined>' is not assignable to type 'string | Promise<string> | OutputInstance<string> | undefined'.
      Type 'OutputInstance<string | undefined>' is not assignable to type 'string | Promise<string> | OutputInstance<string> | undefined'.
        Type 'OutputInstance<string | undefined>' is not assignable to type 'OutputInstance<string>'
```

Expected: Table item is successfully created.
Actual: Typescript error is thrown.

**Comment by mcfadyeni** [comment]
A temporary workaround seems to be suffixing the range key with `as any` - e.g (using previous example):
```
const dynamoItem = new aws.dynamodb.TableItem("example", {
			tableName: main_table.name,
			hashKey: main_table.hashKey,
			rangeKey: main_table.rangeKey as any,
			item: '{"hashKey": {"S": "hashKey"}, "rangeKey": {"S": "rangeKey"}'
		})
```

**Comment by leezen** [comment]
I think it's that `| undefined` part that is throwing it off the type-checking. If you wanted to avoid the `any` cast, I think you could rewrite this as `main_table.rangeKey.apply(s => s!)` (basically, removing the undefinedness of the output value)

**Comment by mcfadyeni** [comment]
Indeed, that seems to work. Thanks for the advice.

Would this still be considered a bug that shoud be fixed? It seems strange that casting or an `.apply()` is required on the range key but not the hash key.

**Comment by leezen** [comment]
On the `aws.dynamodb.Table` side, I would not consider this is a bug. The `rangeKey` is optional, so modeling the output as `Output<string | undefined>` feels correct to me.

On the `aws.dynamodb.TableItem` side, I can see an argument either way. On the one hand, it would be odd to pass in an `Output<undefined>` here since the semantics of what you’d want is to simply not provide anything. On the other hand, it makes type checks like the one in practice here more difficult to work with. This is tracked generally in https://github.com/pulumi/pulumi/issues/6175 so I'll close this issue in favor of that one.
