### ISSUE TITLE
persistent advanced options diff with aws.elasticsearch.Domain resource

### ISSUE THREAD

**Issue by snstanton** [pulumi/pulumi-aws#1684]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I am seeing a persistent diff in the aws.elasticsearch.Domain resource like the following:

```
    ~ aws:elasticsearch/domain:Domain: (update)
...
      ~ advancedOptions: {
          - override_main_response_version: "false"
        }
```
### Steps to reproduce

The resource is configured as follows:
```
        this.domain = new aws.elasticsearch.Domain(domainName, {
                elasticsearchVersion: "7.7",
                clusterConfig: {
                    instanceType: "t3.small.elasticsearch"
                },
                ebsOptions: {
                    ebsEnabled: true,
                    volumeSize: 10,
                    volumeType: "gp2"
                },
                advancedOptions: {
                    "rest.action.multi.allow_explicit_index": "true",
                    override_main_response_version: "false"
                },
                snapshotOptions: {
                    automatedSnapshotStartHour: 23
                }
            });
```

Note that the resource existed prior to the opensearch change, which might be relevant given the option in question.

Expected: 

No diff.

Actual: 

A persistent diff.

**Comment by mikhailshilkov** [comment]
I tried the repro today but I am not getting any diffs after the original deployment. Maybe it was a point-in-time issue indeed. I'll go ahead and close the issue as fixed/not actionable.

**Comment by stooj** [comment]
Reopening this as I've been able to reproduce it consistently.

1. `override_main_response_version` is not a recognised input so trying to set it will result in an error: `ValidationException: Unrecognized advanced option 'override_main_response_version' passed in advancedOptions`
2. The behaviour isn't triggered unless `advanced_options` is set (it can be empty)
3. Because Pulumi doesn't see it as an Input, `ignore_changes=["advanced_options.override_main_response_version"]` has no effect (a diff is still produced on every `pulumi` operation.

Sample code:

```python
import pulumi_aws as aws

example_domain = aws.opensearch.Domain(
    "example",
    domain_name="example",
    engine_version="OpenSearch_3.1",
    cluster_config={
        "instance_type": "t3.small.search",
    },
    ebs_options={
        "ebs_enabled": True,
        "volume_size": 10,
        "volume_type": "gp2",
    },
    tags={"Domain": "TestDomain", "owner": "stooj"},
    advanced_options={},
)
```


Consistent diff:

```
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::8213::pulumi:pulumi:Stack::8213-dev]
    ~ aws:opensearch/domain:Domain: (update)
        [id=arn:aws:es:eu-west-3:052848974346:domain/example]
        [urn=urn:pulumi:dev::8213::aws:opensearch/domain:Domain::example]
        [provider=urn:pulumi:dev::8213::pulumi:providers:aws::default_7_10_0::051c02a3-64f3-4db9-a5ed-ff4f126c218b]
      ~ advancedOptions: {
          - override_main_response_version     : "true"
        }
Resources:
    ~ 1 to update
    1 unchanged
```

I've reproduced this with `pulumi-aws==7.10.0` and `pulumi-aws==7.16.0`

This issue also means that setting any other `advancedOptions` are ignored as well. I set `indices.query.bool.max_clause_count: "1023"` during my testing and now get a permanent diff on that as well:

```
pulumi up --diff
Previewing update (dev)

  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::8213::pulumi:pulumi:Stack::8213-dev]
    ~ aws:opensearch/domain:Domain: (update)
        [id=arn:aws:es:eu-west-3:052848974346:domain/example]
        [urn=urn:pulumi:dev::8213::aws:opensearch/domain:Domain::example]
        [provider=urn:pulumi:dev::8213::pulumi:providers:aws::default_7_16_0::bd9892fa-e131-4303-a1cb-da2dc8ac3de9]
      ~ advancedOptions: {
          - indices.query.bool.max_clause_count: "1023"
          - override_main_response_version     : "true"
        }
Resources:
    ~ 1 to update
    1 unchanged
```

**Comment by stooj** [comment]
This upstream bug is related: [[Bug]: ValidationException: Unrecognized advanced option 'override_main_response_version' passed in advancedOptions · Issue #27371 · hashicorp/terraform-provider-aws](https://github.com/hashicorp/terraform-provider-aws/issues/27371)

**Comment by corymhall** [comment]
I just tried to reproduce this today and I have not been able to. I'll leave this open for a little bit to see if anyone can provide a consistent repro, but otherwise I'll close this issue.

If anyone is consistently seeing this let me know the specific region you are deploying to in case there are differences between regions.
