### ISSUE TITLE
GetOutput Functions Fail on Preview when using an Output from a Locally Created Resource

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-aws#1826]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
As a developer, I want to be able to use Pulumi's `getOutput` functions (eg- `aws.ssm.getParamterOutput` vs `aws.ssm.getParamter`), so that I can read values from AWS after they've been created. In the `getParameterOutput` example, I expect Pulumi to wait until the Output<string>, that represents the newly created SSM Parameter, to be resolved before executing the `getParameterOutput` call.

However, when `aws.ssm.getParameterOutput` is used to target a resource that is created in the same Pulumi project, the program fails during a `pulumi preview`, but successfully works when skipping preview using `pulumi up -f`. This leads me to believe during `preview`, the two resources are being created in parallel, but not during `up`.

### Steps to reproduce

1. Create new Pulumi Project and Stack.
2. See sample code below.
3. Execute `pulumi preview` (and see error)
4. Execute `pulumi up -f` (and should succeed)

Expected:  `pulumi preview` should succeed.
Actual:  `pulumi preview` errors and reports "* Error describing SSM parameter (my-param): ParameterNotFound:".

Sample Code (index.ts):
```typescript
import * as aws from "@pulumi/aws";

// This program fails on "pulumi preview" but succeeds on "pulumi up -f"
const parameter = new aws.ssm.Parameter("some-param", {
        type: "String",
        name: "my-param",
        value: "yay!",
    });

const outParam = aws.ssm.getParameterOutput({
    name: parameter.name
});

export const outputValue = outParam.value;
```

**Comment by lukehoban** [comment]
This is an interesting case. 

The results you are seeing are by design. But I can see why that is surprising. 

A workaround would be to make this call inside an apply on `.id`. 

The code you have is roughly equivalent to an invoke inside an apply on `.name`. However, because you passed `name` as a known input, we propagate that as a known output during preview. This is in general necessary to get accurate previews. But in this case, it means that we think we have all the information we need to make the invoke call, when in practice we don’t. Making the invoke depends (via apply, or else passing an output as an input) on any output property that is not “known” will make this work. 

I am not sure there will be any way to make this work directly as written without a significant negative impact on preview accuracy in general unfortunately.

**Comment by phillipedwards** [comment]
Thanks for the detailed response. I was curious about apply's behavior, as it relates to `name` vs something like `id` or `arn`. 

Is it fair to say any input provided to a resource during creation is marked as "known"? Going further, `apply` on a known property would not wait until the physical resource has been created? Or is `name` a special case?

**Comment by mikhailshilkov** [comment]
This isn't specific to AWS, we should track this issue in https://github.com/pulumi/pulumi/issues/10550
