### ISSUE TITLE
Import of SpotInstanceRequest duplicates property instanceInterruptionBehavior

### ISSUE THREAD

**Issue by chivandikwa** [pulumi/pulumi-aws#1866]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Importing an existing AWS SpotInstanceRequest duplicates the property instanceInterruptionBehavior

`instanceInterruptionBehavior: "stop",
instanceInterruptionBehavior: "stop",`

A diagnostic warning is also issues for this.

_Diagnostics:
  aws:ec2:SpotInstanceRequest (linux-build2-spot-request):
    warning: One or more imported inputs failed to validate. This is almost certainly a bug in the `aws` provider. The import will still proceed, but you will need to edit the generated code after copying it into your program.
    warning: aws:ec2/spotInstanceRequest:SpotInstanceRequest resource 'linux-build2-spot-request' has a problem: Conflicting configuration arguments: "instance_interruption_behaviour": conflicts with instance_interruption_behavior. Examine values at 'SpotInstanceRequest.InstanceInterruptionBehaviour'.
    warning: aws:ec2/spotInstanceRequest:SpotInstanceRequest resource 'linux-build2-spot-request' has a problem: Conflicting configuration arguments: "instance_interruption_behavior": conflicts with instance_interruption_behaviour. Examine values at 'SpotInstanceRequest.InstanceInterruptionBehavior'._

Without fixing this on attempt to update the resources Pulumi will now attempt to delete that resource. Manually removing the duplicate however fixes the issues.

### Steps to reproduce

1. Import and existing AWS Spot Instance request with command `pulumi import aws:ec2/spotInstanceRequest:SpotInstanceRequest name id
2. Notice the diagnostic error
3. Copy import code to your stack
4. Run Pulumi preview and notice that it attempts to delete the resource

Expected:  The resource to be imported without a diagnostic warning and duplicate field
Actual:  The resource is imported with a diagnostic warning and duplicate field

**Comment by guineveresaenger** [comment]
Hi @chivandikwa - thank you for filing this issue. ❤️ 

Can you verify the version of Pulumi you're using? 
We've been shipping a lot of updates to Pulumi Import recently so if you could verify this bug on the most recent version, that would be very helpful!

The error message notwithstanding, this seems like it is an issue with Pulumi itself rather than this specific provider.

**Comment by chivandikwa** [comment]
Hi @guineveresaenger I was using version 3.27.0

**Comment by mikhailshilkov** [comment]
I ran the same import command today and did not get a duplicate `instanceInterruptionBehavior`. I believe we shipped a few improvements in import behavior since Match 2022, so I'll go ahead and close this issue as fixed. If anyone still experience the same problem, please report back a repro program to create a request which would then fail to import. Thank you!

Here is my imported code:

```ts
const name2 = new aws.ec2.SpotInstanceRequest("name2", {
    ami: "ami-059c...",
    associatePublicIpAddress: true,
    instanceInterruptionBehavior: "stop",
    instanceType: "r7i.large",
    keyName: "blah",
    privateIp: "172.31.12.40",
    rootBlockDevice: {
        iops: 100,
        volumeSize: 8,
        volumeType: "gp2",
    },
    securityGroups: ["default"],
    spotPrice: "0.132300",
    subnetId: "subnet-f8834593",
    validFrom: "0001-01-01T00:00:00Z",
    validUntil: "0001-01-01T00:00:00Z",
    vpcSecurityGroupIds: ["sg-192..."],
}, {
    protect: true,
});
```
