### ISSUE TITLE
Add support for nodejs16.x.x lambda runtime

### ISSUE THREAD

**Issue by JonNode28** [pulumi/pulumi-aws#1955]
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

AWS recently [added node js 16 to it's list of supported Lambda runtimes](https://aws.amazon.com/about-aws/whats-new/2022/05/aws-lambda-adds-support-node-js-16/) but the pulumi aws provider only supports up to nodejs14.x

### Affected area/feature

@pulumi/aws

**Comment by t0yv0** [comment]
Thank you for reporting this @JonNode28 

Can you clarify a little bit which is the case:

- you cannot provision a Lambda with a nodejs 16 runtime because the Pulumi AWS SDK does not give you API to do that, or fails to accept it

- you are trying to actually run some Pulumi code inside a lambda and that code does not support nodejs 16 runtime

I've assumed it's the former and transferred the issue to pulumi-aws repository where we can fix it, but please correct me if it is something more involved.

**Comment by chrisui** [comment]
Confirming that there is a need for [this version bump](https://github.com/pulumi/pulumi-aws/issues/1953) to allow nodejs 16 to work as a runtime.

**Comment by evanwang0** [comment]
I am still having issues using `nodejs16.x` with `@pulumi/aws` at `v5.5.0`. Getting the following error:
```
aws:lambda/function:Function resource 'function' has a problem: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 dotnet6 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2], got nodejs16.x. Examine values at 'Function.Runtime'.
```

Unclear to me if this problem exists in the underlying terraform provider.

**Comment by rarous** [comment]
I have the same issue. Symbol `aws.lambda.Runtime.NodeJS16dX` doesn't exist and I get the same runtime error when `"nodejs16.x"` value is used.

**Comment by pbredenberg** [comment]
I'm on v5.6.0 and still not seeing `aws.lambda.Runtime.NodeJS16dX`

**Comment by rarous** [comment]
@pbredenberg symbol is missing, but value `nodejs16.x` works.

**Comment by stack72** [comment]
@rarous is correct - there is no enum value for nodejs16 - we will get that added

**Comment by pbredenberg** [comment]
Thank you!
