### ISSUE TITLE
prompt user for `aws login`

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi-aws#1968]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Idk if this is reasonable to implement, but it would be nice to improve this flow
```
kdixler@kdixler-20xw004aus ~/Documents/aws-python % pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/dixler/aws-python/dev/previews/a96bbfbb-02d0-4d09-bf91-9c83d8ed1c48

     Type                 Name            Plan       Info
 +   pulumi:pulumi:Stack  aws-python-dev  create     
     └─ aws:s3:Bucket     my-bucket                  1 error
 
Diagnostics:
  aws:s3:Bucket (my-bucket):
    error: unable to discover AWS AccessKeyID and/or SecretAccessKey - see https://pulumi.io/install/aws.html for details on configuration
 

255 kdixler@kdixler-20xw004aus ~/Documents/aws-python % aws sso login
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.us-west-2.amazonaws.com/

Then enter the code:

<redacted>
Successully logged into Start URL: <redacted>
kdixler@kdixler-20xw004aus ~/Documents/aws-python % pulumi up
Previewing update (dev)

View Live: <redacted>

     Type                 Name            Plan       
 +   pulumi:pulumi:Stack  aws-python-dev  create     
 +   └─ aws:s3:Bucket     my-bucket       create     
 
Resources:
    + 2 to create

Do you want to perform this update?  [Use arrows to move, enter to select, type to filter]
  yes
> no
  details
...

```

**Comment by stack72** [comment]
@dixler even by popping this open, it won't allow us to pick up the credentials. The credentials for the provider need to either be a profile, shared credentials file, env vars or pulumi config variants

I am going to close this out as a by-design as we are restricted to passing the configuration to the underlying provider in this way

**Comment by dixler** [comment]
Apparently this error message is more common than forgetting to set up a required config value(which I do all the time).

**Comment by dixler** [comment]
> Which "required config value" ?

like whenever a user has a

```typescript
const foo = config.require("my-key")
```

inside of their program and they make a new stack, but their new stack doesn't have that value configured.

**Comment by stack72** [comment]
oh I see what you are saying - yeah this message will happen any time their creds are not configured when running a preview / update of pulumi-aws

**Comment by dixler** [comment]
I think I can improve the error message so there are easily copyable command suggestions to resolve this issue like

`aws sso login`

`aws configure`

in the spirit of pulumi/pulumi#9640

**Comment by guineveresaenger** [comment]
Assigning myself as @stack72 and I came up with some ideas on improvements.

The overall idea is to 
1. bring a checklist of common issues to the terminal output
2. actually cover in the Installation guide common struggles (specifically the fact that `aws:region` is required); more on that once I have screenshots of some scenarios.

**Comment by guineveresaenger** [comment]
So I tested the most common new user scenario:

**Setup**
- No awsconfig
- vanilla `pulumi new typescript` - while many of our how-tos specify `pulumi new aws-typescript`, we [do have many that don't](https://www.pulumi.com/registry/packages/aws/how-to-guides/s3-website/#step-1-create-a-new-project-from-a-template)

**With no env vars set**

<img width="1170" alt="test2_error_no_creds" src="https://user-images.githubusercontent.com/13116240/179622482-5e3a779d-4cf6-4e28-8e85-18582a57a7cf.png">

**After setting AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN** (but not the region)

<img width="1207" alt="test2_error_no_region" src="https://user-images.githubusercontent.com/13116240/179622635-225de073-2d05-438d-97bd-612f5b50b969.png">

The error is exactly the same.

When printing the error that gets passed from AWS, we get a bit more information:

**With no env vars set**

<img width="2428" alt="test3_error_no_creds" src="https://user-images.githubusercontent.com/13116240/179622920-0c0a6d7f-b1f7-4769-adde-f044318731ff.png">

**After setting AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN** (but not the region)

<img width="1506" alt="test3_error_no_region" src="https://user-images.githubusercontent.com/13116240/179623016-825db465-489c-4028-be56-851ed1d5eede.png">

We can see that the first error is due to not having set access credentials, and the second one to not having specified a region.

I would suggest two things:

1. Alter #2051 to include a short checklist such as this: 

<img width="984" alt="checklist_suggestion" src="https://user-images.githubusercontent.com/13116240/179626744-edb05e9d-bc86-41b2-8d43-0d26fbef02f0.png">

2. Include a similar checklist at the very top of [the package installation configuration guide](https://www.pulumi.com/registry/packages/aws/installation-configuration/)

**Comment by guineveresaenger** [comment]
If we agree that this is a good improvement, the Providers team will include this format in all of the major providers.

**Comment by guineveresaenger** [comment]
Registry changes here: https://github.com/pulumi/registry/pull/1252

**Comment by guineveresaenger** [comment]
Closed via https://github.com/pulumi/registry/pull/1252 and #2051 .
