### ISSUE TITLE
Upload less by default into `aws.serverless.Function`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#209]
In addition to allowing users to control what gets uplaoded to lambdas (https://github.com/pulumi/pulumi-aws/issues/35), we should also ensure that we default to a reasonable and useful set of files to upload into the Lambda.

Even if we limit to `node_modules` by default, this will in general contain lots of pacakges which are needed at Pulumi deployment time, but not at runtime.  Unfortuantely, we have not metadata to tell us for sure which is which.

The only robust approach I can imagine is to ask Pulumi users to provide a `dependencies` object as configuration in their Pulumi program, to be used to reconstruct a `node_modules` folder to use for the upload, instead of using the real `node_modules` folder in the deployment context.

**Comment by CyrusNajmabadi** [comment]
I thnk we're actually ok here.  We now have the behavior, by default, that we won't include `@pulumi` packages (or their dependencies).  That trims down things a lot and makes it much more likely that the set of modules included are the ones that the user needs themselves.

We've also made it possible for those packages to include a specific `pulumi: { runtimeDependencies: { ... } }` section.  This is important in the case where the user captures-by-value some part of the pulumi runtime-API surface that itself depends on other modules.  An example of this is how we support the `HttpServer` type at the `@pulumi/cloud` layer.  To support exposing the nodejs-style http handler, we defer (at runtime) to some helper libs.  In order to pull these in, the respective `@pulumi/cloud-xxx` lib mentions tehse as runtime deps so that the user themselves doesn't have to explicitly reference them.  This then pulls in those deps, without pulling in all the deployment time deps that `@pulumi/cloud-xxx` transitively pulls in.
