### ISSUE TITLE
BucketV2 aliasing not working

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-aws#2150]
### What happened?

A customer is trying to use the aliasing from `Bucket` => `BucketV2` to upgrade the AWS provider. Unfortunately, it's forcing a replace

![image](https://user-images.githubusercontent.com/1622940/191564117-1db6ddb8-0e25-4c14-a998-0d2a09c32233.png)

### Steps to reproduce

Define a bucket

```
        aws.s3.Bucket(
            name,
            aws.s3.BucketArgs(
                acl=aws.s3.CannedAcl.PRIVATE,
                force_destroy=True,
                lifecycle_rules=args.lifecycle_rules,
                loggings=args.loggings,
                object_lock_configuration=args.object_lock_configuration,
                server_side_encryption_configuration=args.server_side_encryption_configuration,
                versioning=aws.s3.BucketVersioningArgs(enabled=True),
                tags=self.args.tags
            ),
            opts=self.child_opts,
        )
```

then try and create an alias to the v1 bucket like so

```
        self.bucket = aws.s3.BucketV2(
            resource_name=self._name,
            args=aws.s3.BucketV2Args(
                bucket=args.name, 
                object_lock_enabled=args.object_lock_enabled, 
                tags=args.tags
            ),
            opts=pulumi.ResourceOptions(
                parent=self, aliases=[pulumi.Alias(type_='aws:s3/bucket:Bucket')], ignore_changes=['bucket', 'bucket_prefix']
            )
        )
```

### Expected Behavior

The bucket is aliased and a replacement is not created

### Actual Behavior

The provider tries to replace the bucket

### Additional context

Customer is going to try create a small repro

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
So, just to confirm what I'm seeing here:
- The bucket name is unchanged - this is set in the tags in the original
- Force_delete is being removed, but this shouldn't cause replacement
- You're moving from setting `object_lock_configuration` to using `object_lock_enabled` - which doesn flag for replacement. 

It seems likely that the addition `object_lock_enabled` is the source of the issue. 

Possible solutions/workarounds:
- Even though `object_lock_configuration` is deprecated, could you continue using that instead of the top-level `object_lock_enabled` property?
- If you want to use the new property, you could remove the old bucket from your stack (possibly using RetainOnDelete) then import the bucket back into the stack using the V2 bucket.
- The core issue seems related to https://github.com/pulumi/pulumi/issues/9115

Would either of these workarounds work for you @jaxxstorm in this situation?

**Comment by lukehoban** [comment]
@danielrbradley @jaxxstorm Is there a bug here, or is this behaving as designed?  This comment in particular seems to suggest the replacement is expected.

> You're moving from setting object_lock_configuration to using object_lock_enabled - which doesn flag for replacement.

Assuming that's right, this is indeed what we would expect, and users can indeed get the desired end result by taking one of the paths noted in https://github.com/pulumi/pulumi-aws/issues/2150#issuecomment-1254767802.

I'm going to close out as I believe this analysis is correct, but if not, please do re-open with additional details.
