### ISSUE TITLE
Audit for delete-before-recreate

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-aws#221]
I suspect there are several places we should be using delete-before-recreate now that we can.

For instance, I just ran into an issue with ElastiCache SubnetGroups, where I couldn't change the subnets to which one was attached, because it claimed they were in use.  I suspect this is a case where we need to first tear down the ElastiCache ReplicationGroup that references it.

I was going to file an issue just for that case, but then realized we probably ought to do a broader audit.

**Comment by lukehoban** [comment]
I think we should instead focus on https://github.com/pulumi/pulumi/issues/1620 so that users can opt-in to this which would unblock this broadly (plus additional cases).  

Other than actually hitting the need for this, it's difficult to idenitfy from an audit - so I'm inclined to wait on switching the default until we hear specific feedback (or based on identifying opt-in usage via https://github.com/pulumi/pulumi/issues/1620).
