### ISSUE TITLE
Too many WAFv2 types

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-aws#2276]
The WAFv2 module contains a large number of types which causes knock-on impact in other areas.

Downstream issues:
- https://github.com/pulumi/pulumi/issues/11552
- https://github.com/pulumi/pulumi-aws/issues/2250
- https://github.com/pulumi/registry/issues/1481

We need to find a way of reducing the number of types to avoid these issues. One low-complexity solution could be to just change the offending type to a fully untyped "any" type.

**Comment by ploxiln** [comment]
I was able to view the Go package documentation in terminal like this:

```sh
go doc -all github.com/pulumi/pulumi-aws/sdk/v5/go/aws/wafv2 | less
```

interesting to note the scale of the issue:

```
$ go doc -all github.com/pulumi/pulumi-aws/sdk/v5/go/aws/wafv2 | wc -l
  979307
$ go doc -all github.com/pulumi/pulumi-aws/sdk/v5/go/aws/ec2 | wc -l  
   73026
$ go doc -all github.com/pulumi/pulumi-aws/sdk/v5/go/aws/s3 | wc -l 
   22090
```

I was unable to actually use this package because the Go compiler would use over 30 GB of memory on my system trying to compile this package while importing it (before I gave up and killed it).

**Comment by mikhailshilkov** [comment]
This will be fixed by https://github.com/pulumi/pulumi-aws/pull/2589 in 6.0 of the provider
