### ISSUE TITLE
Elesticbeanstalk Environment refers to type that doesn't exist

### ISSUE THREAD

**Issue by david-latacora** [pulumi/pulumi-aws#2358]
### What happened?

On line 476281 in `provider/cmd/pulumi-resource-aws/schema.json` exists the resource "aws:elasticbeanstalk/environment:Environment", in its property "version", it references the type "#/types/aws:elasticbeanstalk/applicationVersion:ApplicationVersion" on line 476403 and that type is never declared in types section of the schema. The value of "version" is supposed to be the name of an `ApplicationVersion` and there is nothing in the schema to enforce that. I haven't noticed this to cause an issue while conventionally using pulumi but it does cause issues for programatic schema traversal which can be crucial for using unsupported languages against the YAML runtime.

### Expected Behavior

There needs to be a "aws:elasticbeanstalk/applicationVersion:ApplicationVersion" key in the "types" section of the schema with the appropriate schema to enforce the name of an applicationVersion.

### Steps to reproduce

Open up schema file and search for "aws:elasticbeanstalk/applicationVersion:ApplicationVersion"
and only one occurrence will be found at line 475986. This is the declaration for the resource and not the type. 

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hi @david-latacora, this appears to be a slight oddity in the schema, but one that's expected by the Pulumi code generation tooling. I'm not super-familiar with how the combination of ref plus type is meant to be interpreted here but looking at the generated SDKs - most resolve to the string type but there appears to be some special handling in nodejs which allows the type to be resolved to a concrete type: https://github.com/pulumi/pulumi-aws/blob/79e8f9e881cbd3aa2b8e9e3a7ce7d5b2be3fc83d/sdk/nodejs/elasticbeanstalk/environment.ts#L470

This is quite possibly related to a concept called "overlays" where parts of some SDKs are hand-written in some languages. So these types are hand-written in some languages, but in other languages it will fall back to being a string.

It's possible that this kind of special handling exists as part of [pulumi-terraform-bridge](https://github.com/pulumi/pulumi-terraform-bridge) rather than the language code generation if you're trying to reverse engineer the implementation. As far as I know the behaviour is working as expected as ref interpretation is an internal implementation which seems to be functioning correctly.

**Comment by mikhailshilkov** [comment]
This is a fascinating find @david-latacora, thank you for filing this issue!

From my quick look, at appears that `#/types/aws:elasticbeanstalk/applicationVersion:ApplicationVersion` actually refers to the resource `aws:elasticbeanstalk/applicationVersion:ApplicationVersion`, not a type with the same name. Apparently, code generation for different languages then interpret this differently: e.g. Node.js literally pointing to the resource, while others like .NET falling back to `string`. I can't imagine this is correct, so I'll reopen the issue for further investigation.

**Comment by david-latacora** [comment]
Thanks @danielrbradley and @mikhailshilkov for looking into this.

>From my quick look, at appears that `#/types/aws:elasticbeanstalk/applicationVersion:ApplicationVersion` actually refers to >the resource `aws:elasticbeanstalk/applicationVersion:ApplicationVersion`, not a type with the same name.
 
 my understanding is that if a ref is prepended is `#/types` then there should be something in types and that it wouldn't be referring to a resource. Is that not correct?

**Comment by mikhailshilkov** [comment]
I'm digging deeper in this and I'll post a summary of my findings next week. Enjoy your weekend @david-latacora!

**Comment by mikhailshilkov** [comment]
This is now tracked more broadly in https://github.com/pulumi/pulumi-aws/issues/2565, so I'll close this issue as a duplicate
