### ISSUE TITLE
`id` name is misleading in aws.iam.OpenIdConnectProvider outputs

### ISSUE THREAD

**Issue by LouisJULIEN** [pulumi/pulumi-aws#2511]
When looking at the output of an instance of `aws.iam.OpenIdConnectProvider`, `id` and `arn` have the same values. 

For example, with an arn equal to `arn:aws:iam::123456:oidc-provider/oidc.eks.eu-central-1.amazonaws.com/id/ABCDEF123456`, I would have expect `id` to be equal to `ABCDEF123456`. That would make more sense to have two different values.

Also, it would suit better the workflow meant to create [EBS CSI Driver](https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html) permissions. In this documentation, `ABCDEF123456` is referred as the ID.

File: [themes/default/content/registry/packages/aws/api-docs/iam/openidconnectprovider/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/iam/openidconnectprovider/)

**Comment by thomas11** [comment]
Hi @LouisJULIEN, thank your for reporting this! The `id` property is a standard part of all of Pulumi's outputs to provide a uniform way of getting the full provider (in this case, AWS) id of a resource.

You're right that in this example, it's redundant and clashes with the `id` parameter in the URL. However, not all AWS resources do not have the ARN in their output, and some other clouds have other ways of accessing their ids, that's when the `id` property is useful.

Even if it's sometimes redundant, I'll close this issue because this `id` is part of Pulumi's uniform output. Feel free to re-open it if you have further concerns.
