### ISSUE TITLE
Error:  Too many list items: Attribute geolocation_routing_policy supports 1 item maximum, but config has 2 declared

### ISSUE THREAD

**Issue by mkreder** [pulumi/pulumi-aws#2587]
### What happened?

In a Route53 Record, I was trying to set a Geo Location Policy with more than one country, but it failed with the following error:

Too many list items: Attribute geolocation_routing_policy supports 1 item maximum, but config has 2 declared. Examine values at 'Record.GeolocationRoutingPolicies'.

### Expected Behavior

Pulumi should be able to create a Geo Location record with multiple countries.

### Steps to reproduce

This is my sample code:

```
  geolocation_routing_policies=[
        aws.route53.RecordGeolocationRoutingPolicyArgs(
            country="DE",
        ),
        aws.route53.RecordGeolocationRoutingPolicyArgs(
            country="FR",
        ),
    ],
```

### Output of `pulumi about`

pulumi about
CLI          
Version      3.72.2
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.41.0
python  unknown

Host     
OS       darwin
Version  13.3.1
Arch     arm64

### Additional context

The argument is called Policies but it errors out if more than 1 is specified.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kpitzen** [comment]
Hi @mkreder - this is due to a change around 5 months ago in the upstream terraform provider:
https://github.com/hashicorp/terraform-provider-aws/commit/71649e80b60eb8aca66e81601d70891eaf41ab56
this provider changed their attribute to accept only entry in the array, which would have caused a breaking change in our provider (as you note, it's named `policies` which is due to it formerly being an array. Supporting their MaxItems = 1 would have renamed the attribute to `policy`, thus breaking existing programs). Though we allow multiple to be specified, the upstream provider catches this at validation time, and throws the error you see here.

I'm going to mark this as working as intended, though I do agree the experience can be a bit confusing.

**Comment by mkreder** [comment]
@kpitzen is there any workaround to be able to specify more than one country? should I open an issue with terraform-provider-aws? The AWS Management console supports specifying more than one country/region in Geo location records.

**Comment by mkreder** [comment]
I think you are right. Based on AWS Management console behavior, a separate record must be created for each region.
