### ISSUE TITLE
ResourceLfTags clears all tags when running code twice

### ISSUE THREAD

**Issue by sdostanko** [pulumi/pulumi-aws#2654]
### What happened?

 I am using `ResourceLfTags`. I got strange behavior for it, when I run it at the first time all our tags created correctly but when this code run again, pulumi sees the difference (but we use the same tags without changes, pulumi must ignore this step) and remove all tags but are not create anyone (but in logs pulumi shows it like replacement), just clean up all tags. 
My function looks like that:
```
const databaseLFTags = new aws.lakeformation.ResourceLfTags("databaseLfTags", {
            database: { name: databaseName },
            lfTags: lfTags
        }, { parent: this });
```
`lfTags` always the same something like that [{key: "foo", value: "123"}, {key: "env", value: "test"}]

### Expected Behavior

When I run the code again and don't change the tags, pulumi should ignore this step. Or if new tags are added, then delete the existing ones and add only those that are present in `lfTags`.

### Steps to reproduce

Run twice 
```
const databaseLFTags = new aws.lakeformation.ResourceLfTags("databaseLfTags", {
            database: { name: databaseName },
            lfTags:  [{key: "foo", value: "123"}, {key: "env", value: "test"}]
        }, { parent: this });
```

### Output of `pulumi about`

![2023-07-31_13-45](https://github.com/pulumi/pulumi-aws/assets/40056437/b5b97fed-075a-44fc-8be9-723cb19a36aa)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @sdostanko - thank you for filing this issue.
In order to help us root cause this, can you please provide us with a program containing a minimum reproduction that we can run on our end?

In addition, can you tell us:

- what version of pulumi you are using?
- what version of the AWS provider you are using?

A general note: it may be that you're running into something related to [this upstream bug](https://github.com/hashicorp/terraform-provider-aws/issues/28448) - even though that particular bug was closed, it is possible that there are unintended side effects on our end.

**Comment by sdostanko** [comment]
I am using 3.75.0 pulumi version and aws-cli 2.4.18, Ubuntu 20.04 LTS.

**Comment by danielrbradley** [comment]
@sdostanko would you be able to provide us a complete, minimal program to run which demonstrates your issue?

This could either be pasted in a comment or be a link to a repo. Thanks!

**Comment by mjeffryes** [comment]
Closing as stale.
