### ISSUE TITLE
Missing new resource `aws_eks_pod_identity_association` in 6.13.0

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-aws#3081]
### What happened?

Hi,

Release https://github.com/pulumi/pulumi-aws/releases/tag/v6.13.0 states it's using https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.29.0

In `5.29.0`, there's a new resource named `aws_eks_pod_identity_association` but it doesn't appear in this provider newest release. Was there anything that prevented the new resource from being imported in the new release?

### Example

n/a

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Looks like this is originating from

https://github.com/hashicorp/terraform-provider-aws/blob/master/internal/provider/fwprovider/provider.go#L376

This code performs tags schema check and filters out resources that don't meet the schema check.  Unfortunately the errors are sent as warnings via tflog and that is completely missed in our provider at the moment, which makes it skip out this resource.

The reason that the check started failing is because as a consequence of https://github.com/pulumi/pulumi-aws/issues/2895 we moved tags handling to Pulumi level and edited the schema of resources to change the Computed attribute on tags.

**Comment by VenelinMartinov** [comment]
@aureq thanks for reporting. We are looking into the issue. Perhaps as a workaround you can try using the resource from the 
native provider? https://www.pulumi.com/registry/packages/aws-native/api-docs/eks/podidentityassociation/

**Comment by t0yv0** [comment]
```
`tags_all` attribute must not be Computed: aws_docdbelastic_cluster
`tags_all` attribute must not be Computed: aws_eks_pod_identity_association
`tags_all` attribute must not be Computed: aws_s3control_access_grant
`tags_all` attribute must not be Computed: aws_s3control_access_grants_instance
`tags_all` attribute must not be Computed: aws_s3control_access_grants_location

```

More resources affected here.
