### ISSUE TITLE
Cannot specify AWS Codepipeline pipelineType V2

### ISSUE THREAD

**Issue by Kody-Quintana** [pulumi/pulumi-aws#3182]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The [aws.codepipeline.Pipeline](https://www.pulumi.com/registry/packages/aws/api-docs/codepipeline/pipeline/) pulumi resource doesn't seem to support V2 codepipelines like they are specified in the API:

https://docs.aws.amazon.com/codepipeline/latest/APIReference/API_PipelineDeclaration.html

Is there any plan to support this? Or am I missing something?

**Comment by guineveresaenger** [comment]
Hi @Kody-Quintana - thank you for filing this enhancement request.

We are awaiting the addition of https://github.com/hashicorp/terraform-provider-aws/issues/34122 upstream in order to pull this into our provider. I've upvoted that issue and suggest you do too.

Once upstream has implemented support for v2, you will shortly be able to use it here as well.

**Comment by Kody-Quintana** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/34122#issuecomment-1889106088

Looks like this has made it into [v5.32.0](https://github.com/hashicorp/terraform-provider-aws/blob/v5.32.0/CHANGELOG.md), any word on getting this to Pulumi?
