### ISSUE TITLE
JSON serialization for `assumeRolePolicy` of aws.iam.Role not working

### ISSUE THREAD

**Issue by geekflyer** [pulumi/pulumi-aws#356]
This should work (as per the type definition), but ends up in an error:

```ts
import * as aws from '@pulumi/aws';

const appName = 'gsuite';

new aws.iam.Role(appName, {
  name: `${appName}-sso-role`,
  
  assumeRolePolicy: {
      Version: '2012-10-17',
      Statement: [
        {
          Effect: 'Allow',
          Principal: {
            Federated: 'arn:aws:iam::1234567890120:saml-provider/gsuite'
          },
          Action: 'sts:AssumeRoleWithSAML',
          Condition: {
            StringEquals: {
              'SAML:aud': 'https://signin.aws.amazon.com/saml'
            }
          }
        }
      ]
    }
});
```

Error:
```
Diagnostics:
  aws:iam:Role (gsuite):
    error: aws:iam/role:Role resource 'gsuite' has a problem: assume_role_policy must be a single value, not a map
```

Versions:
Pulumi: v0.16.1
Pulumi AWS: 0.16.1

**Comment by jen20** [comment]
I can reproduce this on `master` using a simplified program:

Working:

```
const role = new aws.iam.Role("test-role", {
    assumeRolePolicy: JSON.stringify(aws.iam.assumeRolePolicyForPrincipal(aws.iam.Ec2Principal)),
});
```

Not working:

```
const role = new aws.iam.Role("test-role", {
    assumeRolePolicy: aws.iam.assumeRolePolicyForPrincipal(aws.iam.Ec2Principal),
});
```

The actual error produced comes from the Terraform schema ([here][tfschema]), and there has bee no change to that code for quite some time. Adding in execution tracing using `q`, I see that `TransformJSONDocument` is never called for this property. This is curious, since a transformer [is specified][transformer], and it works for other types (for example `policy` on `aws.iam.RolePolicy`).

My best guess so far is that this is something in `tfbridge` which is failing to call the transformer, resulting in a map being passed to the Terraform provider, resulting in the error.

[tfschema]: https://github.com/hashicorp/terraform/blame/86e6481cc661b2ba694d353aab6d11838c066c7c/helper/schema/schema.go#L1562
[transformer]: https://github.com/pulumi/pulumi-aws/blob/master/resources.go#L1307

**Comment by jen20** [comment]
A good amount of tracing later (thanks, DTrace!), I think the issue is in `getInfoFromPulumiName` in `tfbridge`. During the `Check` phase, the Terraform and Pulumi schema are both looked up, but it appears that at least in some cases the Pulumi schema overrides are looked up using the 'native' name instead of the Terraform name, causing `SchemaInfo` to be nil in `MakeTerraformInput`, causing the Transformer not to be run and the map to be passed through to the Terraform provider implementation.

**Comment by jen20** [comment]
This will need a new version of `pulumi/pulumi-terraform` pulling in, but that will resolve this issue (and a few others which are similar).
