### ISSUE TITLE
Interesting flake on TestAccDeleteBeforeCreate

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#3637]
Interesting flake on TestAccDeleteBeforeCreate:

```  error: 1 error occurred:
  	* Retrieving AWS account details: validating provider credentials: retrieving caller identity from STS: 
  	operation error STS: GetCallerIdentity, https response error
        StatusCode: 403, RequestID: 8b1a26fa-db29-43dd-b705-869eadafa74c,
        api error ExpiredToken: The security token included in the request is expired
```

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-aws/issues/3655

**Comment by guineveresaenger** [comment]
Possibly a misconfiguration on our part?
[SO troubleshooting topicwith similar issues](https://stackoverflow.com/questions/73399249/aws-terraform-error-error-configuring-terraform-aws-provider-error-validati)
But the region is set globally for our tests.

[This cron](https://github.com/pulumi/pulumi-aws/actions/runs/8313400173/job/22749856771)  is flaking on the STS GetCallerIdentity credentials verification:
```
 Retrieving AWS account details: validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: <redacted>, api error ExpiredToken: The security token included in the request is expired
 ```
[This is the same error throughout on the flakes](https://github.com/pulumi/pulumi-aws/actions/runs/8331501584/job/22805609347#step:27:642)

What is interesting is that this test _never_ flakes on `master`.

I deleted the EC2 instance that failed to be deleted in our last run.

I wonder if it's an [expiration issue](https://repost.aws/knowledge-center/sts-iam-token-expired) since node tests take just a little over an hour to run?

**Comment by guineveresaenger** [comment]
UPDATE: this is now [flaking on pull requests as well](https://github.com/pulumi/pulumi-aws/actions/runs/8333514081/job/22806982878?pr=3656#step:28:496).

**Comment by t0yv0** [comment]
Flakes on master in https://github.com/pulumi/pulumi-aws/issues/3636 fwiw.. Not sure what's going on here.

**Comment by guineveresaenger** [comment]
Waiting on a runner is what is eating up most of the authenticated time:
```
2024-03-20T18:07:34.4133831Z Requested labels: ubuntu-latest
2024-03-20T18:07:34.4134259Z Job defined at: pulumi/pulumi-aws/.github/workflows/run-acceptance-tests.yml@refs/pull/3664/merge
2024-03-20T18:07:34.4134450Z Waiting for a runner to pick up this job...
2024-03-20T18:07:34.7221118Z Job is waiting for a hosted runner to come online.
2024-03-20T18:07:39.3277658Z Job is about to start running on the hosted runner: GitHub Actions 12 (hosted)
```
(the above is output from a running job after ~15 minutes)

**Comment by guineveresaenger** [comment]
Fixed via #3666

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-aws/actions/runs/8438448044 another instance

**Comment by t0yv0** [comment]
https://github.com/pulumi/ci-mgmt/pull/863 I think ultimately fixed it by doubling the timeout window.
