### ISSUE TITLE
Panic when setting `aws.ecs.Service` `network_configuration` `subnets` to a string instead of a list

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-aws#3865]
### What happened?

* Program gets a list of subnets from config but accidentally used `config.get()` instead of `config.get_object()`
* `pulumi preview` throws a panic for the ecs.service resource that references the subnets.

### Example

Example code is based on customer-provided code which I do not want to share publicly.
Contact me for a link to code.

### Output of `pulumi about`

CLI          
Version      3.113.3
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.32.0
resource  docker  4.5.3
language  python  unknown

Host     
OS       darwin
Version  13.6.6
Arch     x86_64

This project is written in python: executable='/Users/mitch/Downloads/wmg-panic-5070/customer-engineering/customer-support/5070/venv/bin/python3' version='3.10.11'

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com

Dependencies:
NAME           VERSION
pip            23.0.1
pulumi_aws     6.32.0
pulumi_docker  4.5.3
setuptools     65.5.0

### Additional context

Correcting the code to use `get_object()` (and a fix in the code where subnets are referenced) fixes the problem.
But finding the root-cause was hard given the panic output instead of a more prescriptive the error message.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by corymhall** [comment]
This is related to https://github.com/pulumi/pulumi-terraform-bridge/issues/1328 where we want to do some type checking so that we throw a better error than the panic.

When `pulumi-aws` is released with the next version of the bridge it will contain the initial version of the type checker which should help with this. When running with the new type checker you will now get this error from the example code

```console
Diagnostics:
  aws:ecs:Service (service):
    warning: Type checking failed. If any of these are incorrect, please let us know by creating anissue at https://github.com/pului/pulumi-terraform-bridge/issues.
    warning: urn:pulumi:dev::pulumi-python-app::aws:ecs/service:Service::service verification warning: expected array type, got string type: Examine values at networkConfiguration.subnets
```

At the moment it will still throw the panic because we are only using a warning for the type checker. At some point this will turn into an error in which case the panic will go away. This can be previewed with the `PULUMI_ERROR_TYPE_CHECKER=true` environment variable.

**Comment by corymhall** [comment]
In the latest release we now show a better warning and do not throw a panic. I'm going to close this, but please let us know if you still see any issues that we should fix.
