### ISSUE TITLE
OpenSeachServerless ServerlessAccessPolicy.Policy shows diff when there are no changes, causing an update failure.

### ISSUE THREAD

**Issue by automagic** [pulumi/pulumi-aws#3873]
### What happened?

After creation of the resource, all subsequent updates failed to do because Pulumi and AWS disagree on the order of the properties (causing it to appear as a diff).   AWS rejects the change because the are acutally no changes, with the following:

```operation error OpenSearchServerless: UpdateAccessPolicy, https response error StatusCode: 400, RequestID: 0041349d-bd0b-4eac-bfa9-11d44cac0fb6, ValidationException: No changes detected in policy or policy description```

### Example

n/a

### Output of `pulumi about`

3.113.3

### Additional context

Seems to be an issue at the serializer level, since the Policy is Input<string>

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by corymhall** [comment]
@automagic do you have a example application with steps to reproduce? Thanks!

**Comment by rajephon** [comment]
I am encountering an issue with `aws.opensearch.ServerlessSecurityPolicy`. The `policy` field is a JSON string type, and even though there is no change in its value, running `pulumi preview` shows an update in the Plan. Furthermore, executing `pulumi up` results in the following error:

```
aws:opensearch:ServerlessSecurityPolicy (aoss-network-policy):
  error: updating Security Policy (foobar-network-policy): operation error OpenSearchServerless: UpdateSecurityPolicy, https response error StatusCode: 400, RequestID: ccc02608-xxxx-xxxx-xxxx-c5055ed4d78d, ValidationException: No changes detected in policy or policy description
```
I suspect the issue might be due to AWS detecting changes because the order of fields in the policy JSON string provided by AWS differs from the one we submit. I have not verified this deeply yet.

### Output of `pulumi about`

CLI          
Version      3.112.0
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  14.3
Arch     arm64

**Comment by mikhailshilkov** [comment]
@automagic Can you please provide us with a repro?

**Comment by t0yv0** [comment]
Still would appreciate a repro here @automagic - what is the minimal Pulumi program that makes the system enter this state? I can confirm with @corymhall but I think it is very difficult for us to make progress on this absent a repro.

**Comment by mjeffryes** [comment]
customer reports that this issue does not seem to repro any more
