### ISSUE TITLE
Remove incorrect MaxItems = 1 on AWS ALB Listener

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-aws#418]
This comment

https://github.com/pulumi/pulumi-aws/blob/9647dcf9c2c411913bcfff63c418d04cef429f57/resources.go#L975-L976

was introduced in https://github.com/pulumi/pulumi-aws/commit/276c743ce9dffd245088f2de9f9dfbf8799c0019. As they comment correctly says, this annotation is wrong, and should remove it; as it stands, this causes Terraform conversions to fail and docs to be generated incorrectly.

**Comment by lukehoban** [comment]
This also just blocked me from using the authentication support on ALBs, which requires that two actions be provided (an authentication action and then a forwarding action) - as in https://www.terraform.io/docs/providers/aws/r/lb_listener.html#authenticate-oidc-action.

This will be a breaking change, but it should be a "loud" breaking change in that the name of the property will change, and since it's required deployments will fail early with reasonable error messages about what they need to change after upgrading.

I suggest we make this change soon and release a major version bump if needed.

**Comment by lukehoban** [comment]
We had to revert the fix for this, as it is a breaking change in the provider itself (not just the typings) which doesn't version correctly.  We'll need to see if we can fix this in a (more) compatible way and/or make some fix to how we load/version providers.

**Comment by lukehoban** [comment]
This is blocked on https://github.com/pulumi/pulumi/issues/2389.

**Comment by jen20** [comment]
I think we can do this at the same time as updating to v2.1.0 of upstream.
