### ISSUE TITLE
DLM: Execution role shouldn't be mandatory

### ISSUE THREAD

**Issue by akoenig** [pulumi/pulumi-aws#422]
Creating a Lifecycle Policy (DLM) requires defining an `executionRoleArn`, whereas the CloudFormation definition states [that it is not required](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dlm-lifecyclepolicy.html#cfn-dlm-lifecyclepolicy-executionrolearn).

AWS will create a `default role` when omitting the "execution role ARN".

![screenshot 2019-01-03 at 11 03 40](https://user-images.githubusercontent.com/224910/50632223-7154fa80-0f47-11e9-8655-317a9692dfe5.png)

**Comment by stack72** [comment]
Hi @akoenig 	

Firstly, I must apology for us being so tardy in the reply here - we will try and ensure this doesn't happen anymore. 

So, on inspection of this, I see from the AWS SDK the following:

```
	// A description of the lifecycle policy. The characters ^[0-9A-Za-z _-]+$ are
	// supported.
	//
	// Description is a required field
	Description *string `type:"string" required:"true"`

	// The Amazon Resource Name (ARN) of the IAM role used to run the operations
	// specified by the lifecycle policy.
	//
	// ExecutionRoleArn is a required field
	ExecutionRoleArn *string `type:"string" required:"true"`
```

As you can see, the AWS SDK directly suggests that it is required - this is why this has made it's way down into Pulumi SDKs as required

I am not quite sure why this is the case from the documentation

This is out of our control otherwise we will start failing API requests

Would love to know if you feel we need to raise this with AWS 

@stack72

**Comment by stack72** [comment]
Hi @akoenig 	

I am going to close this out for now - if you feel that we need to investigate this more, then please do comment and we can talk further

Thanks for raising the issue

Paul
