### ISSUE TITLE
`awsx.scheduler.Schedule` option `ScheduleTargetEcsParameters` is missing `serviceConnectConfiguration`

### ISSUE THREAD

**Issue by Defman** [pulumi/pulumi-aws#4380]
### Describe what happened

`awsx.ecs.FargateServiceArgs` has the option `serviceConnectConfiguration` which is not present in `ScheduleTargetEcsParameters`.

See https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html for reference

### Sample program

```typescript
new aws.scheduler.Schedule(detailedResourceName(name), {
  name: detailedResourceName(name),
  groupName: cronScheduleGroup.name,
  scheduleExpression: schedule,
  target: {
    arn: cluster.arn,
    roleArn: cronJobSchedulerRole.arn,
    input: JSON.stringify({
    // @see https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_TaskOverride.html
    cpu: `${cpu}`,
    memory: `${memory}`,
    ecsParameters: {
      serviceConnectConfiguration: {
          enabled: true,
          namespace: clusterHttpNamespace.arn,
      },
      launchType: 'FARGATE',
      networkConfiguration: {
          securityGroups: [securityGroup.id],
          subnets: vpc.privateSubnetIds,
      },
      taskDefinitionArn: cronTaskDefinition.taskDefinition.apply(
          (task) => task!.arn,
      ),
    },
  },
});

```

### Output of `pulumi about`

Does not compile

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
Hey @Defman, thanks for reporting this issue!

From what I can tell this is not present in the AWS APIs either. See: https://docs.aws.amazon.com/scheduler/latest/APIReference/API_EcsParameters.html.

It seems like Service Connect is not supported for the event bridge scheduler integration. I'd recommend getting a feature request for this started in the AWS [container roadmap](https://github.com/aws/containers-roadmap) in order to get it on their radar.

I'm gonna close this issue in the meantime, but don't hesitate to re-open it if there's any un-answered questions.
