### ISSUE TITLE
AWS IAM and other services don´t work anymore (TLS issue)

### ISSUE THREAD

**Issue by timlukastlt** [pulumi/pulumi-aws#4573]
### Describe what happened

Pulumi is attempting to make a request to ```iam.amazonaws.com``` but uses TLS 1.0. Since AWS only supports higher versions of TLS, the request is blocked, as shown in the image below:
![Image](https://github.com/user-attachments/assets/d419b57f-1044-4730-bb6b-4ab2a894034b)

For sts as an example the requests from Pulumi are working because is uses TLS3. ![Image](https://github.com/user-attachments/assets/ea3f57e0-1d9a-4460-bde0-46597731d7aa)

### Sample program

```python

import pulumi
import pulumi_aws as aws

example = aws.iam.get_role(name="example-iam-role")

```

### Log output

The programm just shows creating... for one hour (55-65 minutes)
After that it shows that the connection to iam.amazonaws.com was not possible.

### Affected Resource(s)

We got this error for iam

### Output of `pulumi about`

```
CLI         
Version     3.134.1
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.53.0
language  python  unknown

Host    
OS       debian
Version  12.7
Arch     x86_64

This project is written in python: executable='/app/venv/bin/python' version='3.9.20'

Backend       
Name           3fd5c982165b
URL            s3://our-bucket/test123
User           root
Organizations 
Token type     personal

Dependencies:
NAME        VERSION
pip         23.0.1
pulumi_aws  6.53.0
setuptools  58.1.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
I'm sorry you're running into this @timlukastlt. I'm starting to investigate it and will provide updates as soon as possible!

**Comment by flostadler** [comment]
@timlukastlt I'm not able to reproduce this on my end, but I'm strongly convinced that this was caused by upgrading the provider to use Go 1.23.
This Go update introduced a [minor change to the crypto/tls standard library package](https://tip.golang.org/doc/go1.23#cryptotlspkgcryptotls) that seemed to trip up the AWS firewalls.
The upstream provider was affected by this [same problem](https://github.com/hashicorp/terraform-provider-aws/issues/39311). They fixed it by disabling this experimental key exchange mechanism.
We should do the same on our end as a short term workaround.


@timlukastlt can you try downgrading pulumi-aws to [v6.50.1](https://github.com/pulumi/pulumi-aws/releases/tag/v6.50.1). This one is still using Go 1.22 and shouldn't be affected.

**Comment by flostadler** [comment]
I created a PR that should fix this problem: https://github.com/pulumi/pulumi-aws/pull/4583
Also opened https://github.com/pulumi/pulumi-aws/issues/4582 to correlate other issues and track a long term fix

**Comment by timlukastlt** [comment]
@flostadler thank you for investigating this issue so promptly. I tested with version v6.50.1, and it works with that one.👍

**Comment by flostadler** [comment]
The fix got merged, I kicked off a release that should complete in the next hours
