### ISSUE TITLE
Re-create deployments on API change

### ISSUE THREAD

**Issue by mfergus1** [pulumi/pulumi-aws#471]
If a deployment exists in a stack and changes are made to the API, default to re-deploying the API for associated stages.

**Comment by lukehoban** [comment]
If you are using the raw `aws.apigateway.RestApi` then I think this is just part of the design of the AWS APIs in this space. 

Partly for that reason, we added `aws.apigateway.x.API` (which is being moved now to `awsx.apigateway.APi`) which takes care of this automatically (and also provides easiest ways to specify the API schema).  If you are already using this, then you should be seeing deployments recreated on any update to the API shape (and the stage reprinted to that new deployment). If you are not, could you share a repro case?

**Comment by lukehoban** [comment]
Per an offline conversation, it sounds like @mfergus1 is using the raw `aws.apigateway.Deployment` and related types. Stitching these together to correctly re-deploy the API is somewhat challenging due to the design of the low level API Gateway features, which is a big part of why we introduced `awsx.apigateway.API` to make this easier.

We're tracking the features that @mfergus1 was missing from `awsx.apigateway.API` in other issues, and we unfortunately can't do anything to "fix" the underlying AWS APIs here - so I'll close this one out and we'll focus on closing the gaps in `awsx.apigateway.API`.
