### ISSUE TITLE
application/network load balancers using subnet_mappings need to be deleted for a change

### ISSUE THREAD

**Issue by rswail** [pulumi/pulumi-aws#476]
When using applicationloadbalancer.LoadBalancer, the LB needs to be deleted/created when either the subnet_ids *or* subnet_mappings are changed.

**Comment by stack72** [comment]
Hi @rswail 	

Firstly, I must apologise for the lack of interaction on this issue in a very long time. This is an area we are striving to get better at and will control to work these issues out.

Secondly, in order to try and reproduce this issue, please can you provide us with a minimal configuration that allows us to work out where the error may be coming from?

Thanks again

Paul

**Comment by stack72** [comment]
Hi @rswail 	

Sorry again for the lack of response the first time around. I haven't heard back from you regarding a reproduction so I am going to close this out. If you feel that this needs to reopen, please do see if you can help me reproduce it and I will look into it for you

Thanks again

Paul
