### ISSUE TITLE
`iam.PolicyAttachment` missing warnings about exclusive attachments

### ISSUE THREAD

**Issue by flostadler** [pulumi/pulumi-aws#4872]
The `iam.PolicyAttachment` resource assumes _exclusive_ management of IAM policies. Across the entire AWS account, all of the users/roles/groups to which a single policy is attached must be declared by a single `iam.PolicyAttachment` resource. This means that even any users/roles/groups that have the attached policy via any other mechanism (including other Pulumi resources) will have that attached policy revoked by this resource when it's deleted.

This can be quite surprising to users, especially because there's no mention of this in the [Pulumi docs](https://www.pulumi.com/registry/packages/aws/api-docs/iam/policyattachment).

Investigate why the [warnings from the upstream provider](https://registry.terraform.io/providers/hashicorp/aws/5.78.0/docs/resources/iam_policy_attachment) are not carried into Pulumi docs and make sure this behavior is documented.

**Comment by stooj** [comment]
There's a small display issue in the docs here because hugo doesn't understand `!>` as markup.

We're not very consistent with using these callout boxes, but a `NOTE` is usually just a blockquote:

```
> **NOTE**: This was a triumph
```

And sometimes we use the same for `WARNING`s, eg [aws.iam.GroupMembership](https://www.pulumi.com/registry/packages/aws/api-docs/iam/groupmembership/)

We get the display wrong elsewhere too: see [aws.apigateway.Deployment](https://www.pulumi.com/registry/packages/aws/api-docs/apigateway/deployment/)

![Image](https://github.com/user-attachments/assets/a70af907-c0ec-41ed-bf9d-ee60d960affd)

Ideally we should have different styling for warnings and notes etc, but that's an issue for the [docs](https://github.com/pulumi/docs) team.

**Comment by flostadler** [comment]
@stooj that's interesting, thanks for bringing it up! Those call-outs are converted from the Terraform docs, so something is going wrong in the doc conversion pipeline. I'm gonna have a look and open an issue in the bridge for this

**Comment by t0yv0** [comment]
Is the issue https://github.com/pulumi/pulumi-terraform-bridge/issues/2251 or we need a new one @flostadler ? Thanks.
