### ISSUE TITLE
BucketV2 is missing examples

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-aws#4890]
The BucketV2 type only has one example:

![Image](https://github.com/user-attachments/assets/347ade73-3e15-4468-82dc-14dea3022b5a)

But the Bucket type has many more:

![Image](https://github.com/user-attachments/assets/8712973b-f38b-437d-9a6a-732c53686e17)

That's unfortunate as we are recommending people use BucketV2. I expected them to have the same set of examples.

**Comment by corymhall** [comment]
@joeduffy that's definitely not great! It looks like the root cause of this is just upstream having worse docs between major version 4 & 5. We restored the v4 docs for the "legacy" `Bucket` and use the latest v5 (current) docs for `BucketV2`.

I'll submit a PR to upstream to see if they will accept adding all these examples back, but if they won't accept it I think we can maintain it on our side.

**Comment by joeduffy** [comment]
@corymhall thanks for quickly taking a look. At least it's not a bug on our side. Now that you mention it, I do know a lot of those other capabilities got split out into distinct resources, so that the S3 Bucket was less of a mega monolithic resource. Possible these examples just moved elsewhere?

**Comment by joeduffy** [comment]
Yeah that looks like what largely happened. For instance, the "Using object lifecycle" example seems largely subsumed by the 9(!!) examples on the new [BucketLifecycleConfigurationV2](https://www.pulumi.com/registry/packages/aws/api-docs/s3/bucketlifecycleconfigurationv2/#example-usage) resource. I'll go ahead and close this by design. Sorry for the noise!
