### ISSUE TITLE
AWS ELB(alb) listener rule with extra condition parameters(query-string/http-header)

### ISSUE THREAD

**Issue by MarvinErkes** [pulumi/pulumi-aws#700]
It seems like, that there is no implementation for extra condition parameters(except field and values) like queryStringConfig or httpHeaderConfig.
`{ 
    listenerArn: listenerArn, 
    actions: [{ 
      targetGroupArn: elbTargetGroup.arn, 
      type: "forward", 
    }], 
    conditions: [ 
      { 
        "field":"query-string", 
        "queryStringConfig":{ 
          "values":[ 
            { 
              "key":"abc", 
              "value":"xyz" 
            } 
          ] 
        } 
      } 
    ], 
  };`
Error:
> error: aws:elasticloadbalancingv2/listenerRule:ListenerRule resource 'listener-rule-test' has a problem: condition.0: invalid or unknown key: query_string_config

**Comment by stack72** [comment]
Hi @MarvinErkes 	

As we generate our schemas based on the upstream terraform providers, we can see this isn't supported there either. There is a PR open that is tracking that work

https://github.com/terraform-providers/terraform-provider-aws/pull/8268

As soon as that becomes available in a Terraform provider release, then Pulumi will support it a number of hours later!

I think it's best to track the issue there rather than create the duplicate here. When the release is made, I will add the note here as well

Paul

**Comment by MarvinErkes** [comment]
hi @stack72 
[ALB PR](https://github.com/terraform-providers/terraform-provider-aws/pull/8268) got merged,
are you already working on the implementation?

**Comment by stack72** [comment]
Hi @MarvinErkes 

I expect a release of the upstream terraform provider today - when that hits, I will immediately be able to ship this :)

Stay tuned!

P.
