### ISSUE TITLE
Detect missing storage param for RDS instances

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi-aws#702]
Having noticed the `allocatedStorage` property on `aws.rds.Instance` was optional, I decided to leave it out, to see how AWS would handle it. 

The `preview` succeeded, but the subsequent `up` failed:

![image](https://user-images.githubusercontent.com/274700/63040830-3458cb00-be7b-11e9-9a50-c6c329eab602.png)

If possible, we should fail the preview in this case, since it looks like one of either `allocatedStorage` or `maxAllocatedStorage` is required.

**Comment by lukehoban** [comment]
I don't believe this is expressible in Terraform schema ("one of these two must be set") and so I don't think it's possible for this to be improved at that layer.  We could try to add custom annotations at the Pulumi layer to help here - but they would be a little ad-hoc as there is no schema-driven way to do this either from Terraform or from AWS schema.  I believe all of CloudFormation, Terraform and ARM would also behave in the same way as Pulumi here.

Thoughts @stack72?

**Comment by stack72** [comment]
There isn't anything we can do here. Basically the schema only requires `allocatedStorage` to be set if it's a new DB Instance. A new DB Instance is said to be the case when no `snapshotIdentifier` or `replicateSourceDB` is passed. As you said, we can do something ad-hoc here but this is flakey and we would need to maintain this in the future

FWIW, `maxAllocatedStorage` is only supported with DBs that support autoscaling storage. When this is stored, `allocatedStorage` actually again becomes like a computed value and doesn't really mean anything

FWIW, this is all because the `aws_db_instance` resource became a dumping group for every original RDS scenario.

**Comment by cnunciato** [comment]
Ok, thanks for the explanation, makes sense. I'll go ahead and close.
