### ISSUE TITLE
DynamoDBv2 action not supported

### ISSUE THREAD

**Issue by didiern** [pulumi/pulumi-aws#703]
Hello,

I am trying to define a IoT TopicRule for AWS using the DynamoDBv2 Action. It looks like the property of the TopicRule class is missing. 

Or is there any possibility to use the dynamodb property to define the action of this rule? I tried but it requires hash and sort keys telling me that this is only valid for the dynamodb action and not for dynamodb2 action.

If true there is no possibility to define such AWS action.

Thank you,

**Comment by stack72** [comment]
Hi @didiern 	

As you may or may not know, Pulumi generates it's schema based on the upstream Terraform provider. I am sad to say, there is no support for this functionality yet in the Terraform provider. But, there is an open PR for this work https://github.com/terraform-providers/terraform-provider-aws/pull/7469

Once this PR gets merged and included in a Terraform provider release, it's only a matter of hours until it will be supported in Pulumi

I would suggest you +1 that PR and track it for when it get's merged. I am going to close this out as a duplicate so that there are no multiple places to track the work

Thanks

Paul
