### ISSUE TITLE
Allow management of codecommit specific credentials

### ISSUE THREAD

**Issue by chicocvenancio** [pulumi/pulumi-aws#723]
The AWS CLI allows the creation of service specific credentials to use git with ssh or http credentials. See https://docs.aws.amazon.com/cli/latest/reference/iam/create-service-specific-credential.html
Ideally this would be possible to manage as a pulumi resource.

**Comment by pgavlin** [comment]
The upstream Terraform provider lacks this support: https://github.com/terraform-providers/terraform-provider-aws/issues/3233. Once that issue is fixed, we will pick up support for this resource.

In the meantime, you can work around the lack of support by implementing a [dynamic provider](https://www.pulumi.com/docs/intro/concepts/programming-model/#dynamicproviders) that can manage these credentials.
