### ISSUE TITLE
MSK EncryptionInTransit docs missing from Typescript

### ISSUE THREAD

**Issue by thatarchguy** [pulumi/pulumi-aws#762]
The docs for MSK for Nodejs are missing the section on "encryptionInTransit".

It's included in the Python docs:
https://github.com/pulumi/pulumi-aws/blob/00cb3238e9c4300fd7e47c1bfb798964795f8490/sdk/python/pulumi_aws/msk/cluster.py#L127

This is confusing because the Typescript docs have references to the section, but not docs on the section itself:
https://github.com/pulumi/pulumi-aws/blob/00cb3238e9c4300fd7e47c1bfb798964795f8490/sdk/nodejs/msk/cluster.ts#L234

Here's what `encryptionInTransit` looks like when used:
```
    encryptionInfo: {
        encryptionAtRestKmsKeyArn: kms.arn,
        encryptionInTransit: {
            clientBroker: "TLS_PLAINTEXT",
            inCluster: true,
        }
    },
```

**Comment by stack72** [comment]
Hi @thatarchguy 

Thanks for opening the issue here. Unfortunately, it was confusing from the text:

```
Configuration block for specifying encryption. See below.
```

But there is actually a link here:

<img width="963" alt="Screenshot 2019-10-07 at 19 58 46" src="https://user-images.githubusercontent.com/227823/66332279-081e6f80-e93d-11e9-8c61-670ef8be03f8.png">

Clicking on that will take you to

https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/types/input/#ClusterEncryptionInfo

Sorry about that confusion

Paul
