### ISSUE TITLE
The default description of rds/mysql is "Managed by Terraform"

### ISSUE THREAD

**Issue by nguyenxndaidev** [pulumi/pulumi-aws#775]
The default description of rds/mysql is **Managed by Terraform**

**Comment by stack72** [comment]
Hi @nguyenxndaidev 

what RDS resource are you creating here? Is it a global cluster,  cluster or an instance?

Paul

**Comment by stack72** [comment]
Ping @nguyenxndaidev

**Comment by nguyenxndaidev** [comment]
Hi @stack72 it's an rds instance

**Comment by stack72** [comment]
Hi @nguyenxndaidev 

I cannot see any "description" field on the RDS Cluster, DB Instance or RDS Cluster Instance resources

I think it would be really helpful if you could post some same code that recreates this to see if I can replicate it

Thanks

Paul

**Comment by nguyenxndaidev** [comment]
```
new aws.rds.Instance('example', {
        instanceClass: 'db.t2.micro',
        engine: 'mysql',
        engineVersion: '5.7',
        storageType: 'gp2'
      });
```

**Comment by stack72** [comment]
Hi @nguyenxndaidev 

So I've not been able to recreate this - there is no description field on an RDS DB Instance. I am not sure what resource you seeing here, but there's not any way that I can get a description here.

I have tried the code above - it actually fails due to lots of missing parameters but even when I created the instance, I still didn't get it

Can you take a screenshot from the AWS Console that shows this?

Paul
