### ISSUE TITLE
Create pre-configured aws-sdk clients from aws.Providers

### ISSUE THREAD

**Issue by jonjitsu** [pulumi/pulumi-aws#841]
Currently the underlying sdk is exposed with calls like `new aws.sdk.S3()`, it would be nice to create sdk clients from aws.Provider objects.

**Comment by leezen** [comment]
Could you please provide some more details about your use case? I would typically expect aws.Provider objects in your Pulumi program to describe configuration for deploying your application and not necessarily the same provider that you would want to run your client code with?

**Comment by lukehoban** [comment]
The `aws.sdk` object is currently designed to be used only at runtime (e.g. with a callback used as a `CallbackFunction`).  However - we definitely would like to expand this to be usable also at deployment time.  In the case it is used at deployment time though - it is true that it should be possible to get an instance of the SDK initialized with the same configuration as a given AWS `Provider` instance (or the ambient default provider).  

This is also needed for Policy - I had a note about that (and the general case this issue is tracking) in https://github.com/pulumi/pulumi-policy/issues/122#issuecomment-573111188.

**Comment by iwahbe** [comment]
Since we are no longer including the `aws.sdk` property (https://github.com/pulumi/pulumi-aws/pull/2584), this no longer makes sense.
