### ISSUE TITLE
How to declare objects outside a magic function's handler

### ISSUE THREAD

**Issue by mstn** [pulumi/pulumi-aws#854]
Hi, thanks for this project. It is very great!

I was just wondering if it is possible to define objects outside a handler in such a way that the deployed code would look something like

```
const anObject = ...
const handler = () => { ... }
```
The reason is that, in this way, we can reuse database connections across invocations as explained in AWS lambda documentation:

> Objects declared outside of the function's handler method remain initialized, providing additional optimization when the function is invoked again. For example, if your Lambda function establishes a database connection, instead of reestablishing the connection, the original connection is used in subsequent invocations. We suggest adding logic in your code to check if a connection exists before creating one.

from https://docs.aws.amazon.com/lambda/latest/dg/running-lambda-code.html

**Comment by lukehoban** [comment]
A version of this is possible - but does require a little more work. Specifically, live state in the deployment time program can’t be referenced by the runtime code (it can only be serialized in as input), but you can provide a callback that gets invoked once per compute-host instead of once per request as is often done for this usecase in various severless platforms. 

This uses the `callbackFactory` approach. There are a few examples of this in the examples repro - like https://github.com/pulumi/examples/blob/f02e3335b70928e319183fddb2e4d95185df1006/azure-ts-serverless-url-shortener-global/index.ts#L65 and https://github.com/pulumi/examples/blob/76cdb38ad9c1e6b632910eaadb38263f80f9015b/gcp-ts-slackbot/index.ts#L70.

**Comment by mstn** [comment]
Thanks! I will give a try.
