### ISSUE TITLE
ECR Lifecycle policy update deletes policy

### ISSUE THREAD

**Issue by ChronosWS** [pulumi/pulumi-aws#881]
Pulumi v1.10.1

I have an ECR lifecycle policy in place, deployed with pulumi.  I then made a change to the policy (changing a rules.selection.countNumber field from 1 to 7) and after deployment, the policy no longer existed.  After performing a pulumi refresh, pulumi recognized the policy no longer existed.  A subsequent `pulumi up` fixed the problem.  No intermediate deployments or console operations were performed.

I've seen similar issues with certain objects (IAM policies, S3 bucket object) where an update to the object instead results in its removal, even though during the update it is listed as having been updated, but this is the first time I have been definitive in which change I made and the exact outcome.  Note that when in this situation, `pulumi up` will not result in the object being fixed because the incorrect state has been recorded from the previous operation.

**Comment by leezen** [comment]
That is very concerning as the delete should've been apparent in the preview if it was going to happen. Any chance you could provide a repro of the issue?

**Comment by stack72** [comment]
ping @ChronosWS

**Comment by leezen** [comment]
Closing stale issue

**Comment by jam13** [comment]
This problem is still an issue with current version of pulumi and aws module. The issue seems to be that rather than update the policy it first creates a replacement and then proceeds to delete it. Running `pulumi up` immediately afterwards has no effect, but after a refresh it realises that the resource has been deleted and recreates it correctly.

@pulumi/pulumi 2.7.1
@pulumi/aws 2.13.1
