### ISSUE TITLE
Incorrect typings in LaunchTemplateNetworkInterface : associatePublicIpAddress

### ISSUE THREAD

**Issue by thatsnotright** [pulumi/pulumi-aws#887]
Greetings,

After this change:

https://github.com/pulumi/pulumi-aws/commit/4887b0de8079874123d0adda94cda97b09f003a3

The type of associatePublicIpAddress changed from pulumi.Input<boolean> to pulumi.Input<string>

https://github.com/pulumi/pulumi-aws/blob/e75f2243009dacddd4535d30d504043e26d6bb83/sdk/nodejs/types/input.ts#L5321

I believe this should still be input\<boolean\>.  Is this the case or am I misunderstanding?

**Comment by stack72** [comment]
Hi @thatsnotright 

You are indeed correct - something has been broken in our codegen here causing this

I will get this looked into. Thanks for the report

Paul

**Comment by stack72** [comment]
Hi @thatsnotright 

So, I spent a little time looking into this and this actually happened upstream in the Terraform Provider - https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_launch_template.go#L377

As you can see, they changed that to be a string so that you can pass `1`, `0`, `true` or `false` rather than just a boolean true / false

This isn't something we can control I'm afraid :/ - I'm sorry for this and hope that you understand

Paul
