### ISSUE TITLE
A change to lambda environment variables triggers a change to TargetGroupAttachment

### ISSUE THREAD

**Issue by Erwinvandervalk** [pulumi/pulumi-aws#901]
Hi there,
I'm using pulumi to deploy lambda's and an ALB in AWS and I'm running into an issue.

Here's my scenario:

I have an ALB which forwards traffic to lambda's using a TargetGroupAttachment. When I make a change to the lambda (for example add an environment variable) then this also causes a change in the TargetGroupAttachment. Sometimes this also causes a change in the TargetGroup itself, which it then tries to delete and recreate. Sometimes this results in errors like :
```
Error deleting Target Group: ResourceInUse: .... is currently in use by a listener or a rule.
```

Since the target group attachment only uses the lambda ARN and this doesn't change, i'd expect no changes to be triggered here. 

Here's some of the code I'm using

``` Typescript


    var lambda = new aws.lambda.Function("name", {
            name: "name",
            runtime: aws.lambda.DotnetCore2d1Runtime,
            timeout: 20,
            memorySize: 256,
            handler: "handler",
            publish: true,
            role: role.arn,
            s3Bucket: 'the bucket',
            s3Key: `thezip.zip`, 
            tracingConfig: {
                mode: "Active"
            },            
            environment: {
                   variables: {
                          some_variable: "value"
                   }
            }
        });

            const targetGroup = new aws.lb.TargetGroup(prefixedName, {
                name: prefixedName,
                targetType: "lambda",
                lambdaMultiValueHeadersEnabled: true,
            });
    
    
            new aws.lb.ListenerRule(prefixedName, {
                actions: [{
                    targetGroupArn: targetGroup.arn,
                    type: "forward",
                }],
                conditions: [{
                    hostHeader: {
                        values: [aRecord + ".*"]
                    }
                }],               
                listenerArn: listener.arn,
            });
    
            const permission = new aws.lambda.Permission(prefixedName, {
                statementId: prefixedName,
                action: "lambda:InvokeFunction",
                function: lambda.name,
                principal: "elasticloadbalancing.amazonaws.com",
                sourceArn: targetGroup.arn
            });
    
            const attach = new aws.lb.TargetGroupAttachment(prefixedName, {
                targetId: lambda.arn,
                targetGroupArn: targetGroup.arn,
            }, {
                dependsOn: permission
            });
```

**Comment by leezen** [comment]
Thanks for pointing this out. I couldn't reproduce the situation where the `TargetGroup` actually requires replacement by changing an environment variable for the Lambda function. But I do see the preview show a potential replace of the target group attachment:

```
+-aws:lb/targetGroupAttachment:TargetGroupAttachment: (replace)
...
      ~ targetId: "arn:aws:lambda:us-west-2:12345678901:function:name-deadbef" => output<string>
```

However, when I execute the update, the group itself doesn't change (as expected) since the `arn` of the Lambda function doesn't change. In this case, the preview is conservative, but ends up not executing the replace on the `TargetGroupAttachment`

The next time this happens, could you please provide the detailed diff? I'd like to see why the `TargetGroup` is getting replaced as I could not reproduce this behavior.

As to why this happens, you can see from the preview that for whatever reason, we don't necessarily know what the function's `arn` will be after applying the change. I wouldn't expect that to happen with an `update` on the resource, so this is likely a bug.

In the meantime, as a workaround, you can try to execute a `pulumi up -t <urn>` where `<urn>` is the function urn (which you can get from  `pulumi stack -u`). This will perform a targeted update of the function itself. Then, a subsequent `pulumi up` should show no changes as the function's `arn` hasn't changed. If it does show changes, that would be useful to look at as well to understand what other changes are occurring that aren't related to the function's update.

**Comment by Erwinvandervalk** [comment]
Hi Leezen, Thank you for your great reply! 

In most situations, I only see the targetgroupattachment being flagged as modified (in preview). It's good to know that this is not really being modified. 

As for the TargetGroup being replaced, there may be something else going on as well. I'll try to see today if I can create an isolated repro.

**Comment by Erwinvandervalk** [comment]
Sorry, I've not been able to reproduce this issue. I'll close the issue for now and keep an eye out for it. Thanks again!
