### ISSUE TITLE
route53.get_zone doesn't work with "lift"?

### ISSUE THREAD

**Issue by dieswaytoofast** [pulumi/pulumi-aws#917]
If I try and lift the Output from `acm.Certificate` to use it with `route53.get_zone`, it barfs with the error
    `Exception: invocation of aws:route53/getZone:getZone returned an error: invoking aws:route53/getZone:getZone: Either name or zone_id must be set`

Why am I doing this?
Well, I'm trying to create an ACM certificate with > 10 alternative domains.
The base code looks something like the below
```
certificate = acm.Certificate(
    'blockfi.biz-certificate',
    domain_name= 'blockfi.biz',
    subject_alternative_names=['*.blockfi.biz', 'blockfitrading.biz', '*.blockfitrading.biz'],
    validation_method='DNS',
)

validation = route53.Record(
    'blockfi.biz-zone-record',
    allow_overwrite=True,
    name=certificate.domain_validation_options[0].resource_record_name,
    type=certificate.domain_validation_options[0].resource_record_type,
    records=[
        certificate.domain_validation_options[0].resource_record_value,
    ],
    ttl=60,
    zone_id=route53.get_zone(name=certificate.domain_validation_options[0].domain_name).zone_id,
)
```

Note that if I do something somewhat different, i.e., by indexing off of the list of subject_alternative_name as shown below, then it barfs too - the records seem to get created in completely random domains from the list (perhaps the order in `domain_validation_options` is not the same as in `foo` ????)
```
foo = ['*.blockfi.biz', 'blockfitrading.biz', '*.blockfitrading.biz']
certificate = acm.Certificate(
    ...
    subject_alternative_names=foo
...
validation = route53.Record(
    ...
    name=certificate.domain_validation_options[index_of_element_in_foo].resource_record_name,
...
```

**Comment by leezen** [comment]
`get_zone` expects a `str` and not an `Output` which is why it's throwing an error. Per the other discussion, you should be able to simply use the `zone` object you created instead of trying to use `get_zone`

If you want to split it up, you can either reference the zone via a stack export or you can use `get_zone` in which case, you should pass in the zone name explicitly (vs. trying to use the `Output` from the certificate)

Alternatively, you can use apply to create a new output, e.g. something like
```
    zone_id=certificate.domain_validation_options[0].domain_name.apply(lambda n: route53.get_zone(name=n).zone_id),
```
